/**
 * Canvas Utilities
 *
 * Shared utility functions for canvas operations
 */

import { CanvasNode, CanvasEdge, LayoutPosition, LayoutConfig, ColumnAttribute, MappingRule } from '../core/types';
import { COLUMN_MATCHING } from '../core/canvasConfig';

// ============================================================================
// String Similarity Functions
// ============================================================================

/**
 * Calculate Levenshtein distance between two strings
 */
export function levenshteinDistance(str1: string, str2: string): number {
  const m = str1.length;
  const n = str2.length;
  const dp: number[][] = Array(m + 1)
    .fill(null)
    .map(() => Array(n + 1).fill(0));

  for (let i = 0; i <= m; i++) dp[i][0] = i;
  for (let j = 0; j <= n; j++) dp[0][j] = j;

  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      if (str1[i - 1] === str2[j - 1]) {
        dp[i][j] = dp[i - 1][j - 1];
      } else {
        dp[i][j] = Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]) + 1;
      }
    }
  }

  return dp[m][n];
}

/**
 * Calculate similarity score between two strings (0 to 1)
 */
export function calculateSimilarity(str1: string, str2: string): number {
  if (str1 === str2) return 1.0;

  const s1 = str1.toLowerCase();
  const s2 = str2.toLowerCase();

  if (s1 === s2) return 0.95;

  const maxLen = Math.max(s1.length, s2.length);
  const distance = levenshteinDistance(s1, s2);

  return 1 - distance / maxLen;
}

/**
 * Normalize column name by removing common prefixes/suffixes
 */
export function normalizeColumnName(name: string): string {
  let normalized = name.toLowerCase().trim();

  // Remove common prefixes
  for (const prefix of COLUMN_MATCHING.commonPrefixes) {
    if (normalized.startsWith(prefix)) {
      normalized = normalized.substring(prefix.length);
      break;
    }
  }

  // Remove common suffixes
  for (const suffix of COLUMN_MATCHING.commonSuffixes) {
    if (normalized.endsWith(suffix)) {
      normalized = normalized.substring(0, normalized.length - suffix.length);
      break;
    }
  }

  return normalized;
}

// ============================================================================
// Column Matching Functions
// ============================================================================

/**
 * Find best matching column from a list of target columns
 */
export function findBestMatch(
  sourceColumn: string,
  targetColumns: string[]
): { column: string; confidence: number } | null {
  if (targetColumns.length === 0) return null;

  let bestMatch = targetColumns[0];
  let bestScore = 0;

  const normalizedSource = normalizeColumnName(sourceColumn);

  for (const targetColumn of targetColumns) {
    // Check for exact match first
    if (sourceColumn === targetColumn) {
      return { column: targetColumn, confidence: COLUMN_MATCHING.exactMatchScore };
    }

    // Check for case-insensitive match
    if (sourceColumn.toLowerCase() === targetColumn.toLowerCase()) {
      bestMatch = targetColumn;
      bestScore = 0.95;
      continue;
    }

    // Check normalized match
    const normalizedTarget = normalizeColumnName(targetColumn);
    if (normalizedSource === normalizedTarget) {
      if (0.9 > bestScore) {
        bestMatch = targetColumn;
        bestScore = 0.9;
      }
      continue;
    }

    // Calculate similarity score
    const similarity = calculateSimilarity(sourceColumn, targetColumn);
    if (similarity > bestScore) {
      bestMatch = targetColumn;
      bestScore = similarity;
    }

    // Also check normalized similarity
    const normalizedSimilarity = calculateSimilarity(normalizedSource, normalizedTarget);
    if (normalizedSimilarity > bestScore) {
      bestMatch = targetColumn;
      bestScore = normalizedSimilarity * 0.85; // Slight penalty for normalization
    }
  }

  // Only return if above threshold
  if (bestScore >= COLUMN_MATCHING.similarityThreshold) {
    return { column: bestMatch, confidence: bestScore };
  }

  return null;
}

/**
 * Generate field mappings between source and target columns
 */
export function generateFieldMappings(
  sourceColumns: string[],
  targetColumns: string[]
): MappingRule[] {
  const mappings: MappingRule[] = [];
  const usedTargetColumns = new Set<string>();

  for (const sourceColumn of sourceColumns) {
    // Filter out already used target columns
    const availableTargets = targetColumns.filter(col => !usedTargetColumns.has(col));

    const match = findBestMatch(sourceColumn, availableTargets);

    if (match) {
      mappings.push({
        sourceColumn,
        targetColumn: match.column,
        transformationType: 'direct',
        isAutogenerated: true,
      });
      usedTargetColumns.add(match.column);
    }
  }

  return mappings;
}

// ============================================================================
// Node Layout Functions
// ============================================================================

/**
 * Calculate position for a node in a column
 */
export function calculateNodePosition(
  nodeIndex: number,
  totalNodes: number,
  columnX: number,
  config: LayoutConfig
): LayoutPosition {
  const totalHeight = totalNodes * (config.nodeHeight + config.verticalSpacing);
  const startY = -totalHeight / 2;
  const y = startY + nodeIndex * (config.nodeHeight + config.verticalSpacing);

  return { x: columnX, y };
}

/**
 * Calculate positions for nodes in a column
 */
export function layoutNodesInColumn(
  nodes: CanvasNode[],
  columnX: number,
  config: LayoutConfig
): CanvasNode[] {
  return nodes.map((node, index) => {
    const position = calculateNodePosition(index, nodes.length, columnX, config);
    return {
      ...node,
      position,
    };
  });
}

/**
 * Center nodes vertically in the canvas
 */
export function centerNodesVertically(nodes: CanvasNode[]): CanvasNode[] {
  if (nodes.length === 0) return nodes;

  const yPositions = nodes.map(n => n.position.y);
  const minY = Math.min(...yPositions);
  const maxY = Math.max(...yPositions);
  const centerOffset = -(minY + maxY) / 2;

  return nodes.map(node => ({
    ...node,
    position: {
      x: node.position.x,
      y: node.position.y + centerOffset,
    },
  }));
}

// ============================================================================
// Edge Path Generation
// ============================================================================

/**
 * Generate a curved Bezier path for an edge
 */
export function generateCurvedPath(
  sourceX: number,
  sourceY: number,
  targetX: number,
  targetY: number
): string {
  const offset = Math.abs(targetX - sourceX) * 0.3;
  const controlPoint1X = sourceX + offset;
  const controlPoint1Y = sourceY;
  const controlPoint2X = targetX - offset;
  const controlPoint2Y = targetY;

  return `M ${sourceX} ${sourceY} C ${controlPoint1X} ${controlPoint1Y} ${controlPoint2X} ${controlPoint2Y} ${targetX} ${targetY}`;
}

/**
 * Generate a stepped path for an edge
 */
export function generateSteppedPath(
  sourceX: number,
  sourceY: number,
  targetX: number,
  targetY: number
): string {
  const midX = (sourceX + targetX) / 2;

  return `M ${sourceX} ${sourceY} L ${midX} ${sourceY} L ${midX} ${targetY} L ${targetX} ${targetY}`;
}

// ============================================================================
// Node Filtering Functions
// ============================================================================

/**
 * Filter nodes by entity type
 */
export function filterNodesByType(nodes: CanvasNode[], entityType: string): CanvasNode[] {
  return nodes.filter(node => {
    const data = node.data as any;
    switch (entityType) {
      case 'raw':
        return data.isRawFile === true;
      case 'curated':
        return data.isCuratedFile === true;
      case 'consumption':
        return data.isConsumptionFile === true;
      default:
        return false;
    }
  });
}

/**
 * Filter edges connected to a specific node
 */
export function getConnectedEdges(nodeId: string, edges: CanvasEdge[]): CanvasEdge[] {
  return edges.filter(edge => edge.source === nodeId || edge.target === nodeId);
}

/**
 * Get all source nodes for a target node
 */
export function getSourceNodes(targetNodeId: string, nodes: CanvasNode[], edges: CanvasEdge[]): CanvasNode[] {
  const sourceIds = edges
    .filter(edge => edge.target === targetNodeId)
    .map(edge => edge.source);

  return nodes.filter(node => sourceIds.includes(node.id));
}

/**
 * Get all target nodes for a source node
 */
export function getTargetNodes(sourceNodeId: string, nodes: CanvasNode[], edges: CanvasEdge[]): CanvasNode[] {
  const targetIds = edges
    .filter(edge => edge.source === sourceNodeId)
    .map(edge => edge.target);

  return nodes.filter(node => targetIds.includes(node.id));
}

// ============================================================================
// Validation Functions
// ============================================================================

/**
 * Check if a node name is valid
 */
export function isValidNodeName(name: string): boolean {
  if (!name || name.trim().length === 0) return false;
  if (name.length > 100) return false;

  // Check for reserved keywords
  const lowerName = name.toLowerCase();
  const reservedKeywords = ['select', 'from', 'where', 'join', 'table', 'database'];
  if (reservedKeywords.includes(lowerName)) return false;

  // Check for valid characters (alphanumeric, underscore, hyphen)
  const validPattern = /^[a-zA-Z0-9_-]+$/;
  return validPattern.test(name);
}

/**
 * Check if an attribute name is valid
 */
export function isValidAttributeName(name: string): boolean {
  if (!name || name.trim().length === 0) return false;
  if (name.length > 64) return false;

  const validPattern = /^[a-zA-Z_][a-zA-Z0-9_]*$/;
  return validPattern.test(name);
}

/**
 * Sanitize node name
 */
export function sanitizeNodeName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '_')
    .substring(0, 100);
}

// ============================================================================
// Data Type Utilities
// ============================================================================

/**
 * Infer data type from column name and sample data
 */
export function inferDataType(columnName: string, sampleData?: any): string {
  const name = columnName.toLowerCase();

  // Check column name patterns
  if (name.includes('id') || name.endsWith('_id')) return 'integer';
  if (name.includes('email') || name.includes('mail')) return 'string';
  if (name.includes('phone') || name.includes('mobile')) return 'string';
  if (name.includes('date') && !name.includes('update')) return 'date';
  if (name.includes('timestamp') || name.includes('created') || name.includes('updated')) return 'timestamp';
  if (name.includes('amount') || name.includes('price') || name.includes('cost')) return 'float';
  if (name.includes('count') || name.includes('quantity')) return 'integer';
  if (name.includes('flag') || name.includes('is_') || name.includes('has_')) return 'boolean';
  if (name.includes('json') || name.includes('metadata')) return 'json';
  if (name.includes('tags') || name.includes('categories')) return 'array';

  // Check sample data if available
  if (sampleData !== undefined && sampleData !== null) {
    const type = typeof sampleData;
    if (type === 'number') {
      return Number.isInteger(sampleData) ? 'integer' : 'float';
    }
    if (type === 'boolean') return 'boolean';
    if (Array.isArray(sampleData)) return 'array';
    if (type === 'object') return 'json';
  }

  // Default to string
  return 'string';
}

/**
 * Get display name for data type
 */
export function getDataTypeDisplay(dataType: string): string {
  const typeMap: Record<string, string> = {
    string: 'String',
    integer: 'Integer',
    float: 'Float',
    boolean: 'Boolean',
    date: 'Date',
    timestamp: 'Timestamp',
    json: 'JSON',
    array: 'Array',
  };

  return typeMap[dataType] || 'Unknown';
}
