/**
 * Canvas Core Types
 *
 * Shared TypeScript types for all canvas implementations
 */

import { Node, Edge } from 'reactflow';

// ============================================================================
// Entity Types
// ============================================================================

export type EntityType = 'raw' | 'curated' | 'consumption' | 'gold';

export type DataType = 'string' | 'integer' | 'float' | 'boolean' | 'date' | 'timestamp' | 'json' | 'array';

export interface ColumnAttribute {
  name: string;
  type: DataType;
  nullable?: boolean;
  isPrimaryKey?: boolean;
  isForeignKey?: boolean;
  isNew?: boolean;
  description?: string;
}

export interface EntityData {
  id: string;
  label: string;
  entityType: EntityType;
  attributes: ColumnAttribute[];
  tableName?: string;
  schemaName?: string;
  scdType2?: boolean;
  isExpanded?: boolean;
  position?: { x: number; y: number };
}

// ============================================================================
// Node Types
// ============================================================================

export interface BaseNodeData {
  label: string;
  onUpdate?: (id: string, label: string, attributes: ColumnAttribute[], edited: boolean, scdType2?: boolean) => void;
  onDelete?: (id: string) => void;
  onExpand?: (id: string) => void;
  onCollapse?: (id: string) => void;
}

export interface RawNodeData extends BaseNodeData {
  isRawFile: boolean;
  attributes: ColumnAttribute[];
  fileName?: string;
  filePath?: string;
}

export interface CuratedNodeData extends BaseNodeData {
  isCuratedFile: boolean;
  attributes: ColumnAttribute[];
  scdType2?: boolean;
  isVisible?: boolean;
  mappedTo?: string[]; // IDs of consumption entities this is mapped to
}

export interface ConsumptionNodeData extends BaseNodeData {
  isConsumptionFile: boolean;
  attributes: ColumnAttribute[];
  outputColumns?: ColumnAttribute[];
  isExpanded?: boolean;
  mode?: 'continuous' | 'triggered';
  environment?: 'development' | 'production';
}

export type CanvasNodeData = RawNodeData | CuratedNodeData | ConsumptionNodeData | BaseNodeData;

export type CanvasNode = Node<CanvasNodeData>;

// ============================================================================
// Edge Types
// ============================================================================

export type RelationshipType = 'field_mapping' | 'entity_mapping' | 'transformation' | 'aggregation';

export interface EdgeData {
  relationshipType?: RelationshipType;
  mappingRules?: MappingRule[];
  transformationType?: string;
  sourceField?: string;
  targetField?: string;
}

export type CanvasEdge = Edge<EdgeData>;

// ============================================================================
// Mapping Types
// ============================================================================

export interface MappingRule {
  sourceColumn: string;
  targetColumn: string;
  transformationType?: 'direct' | 'concat' | 'split' | 'calculate' | 'lookup' | 'nlp';
  transformationLogic?: string;
  isAutogenerated?: boolean;
}

export interface FieldMapping {
  id: string;
  raw: string;
  curated: string;
  isNewColumn?: boolean;
  isControlColumn?: boolean;
  transformationType?: string;
  transformationDetails?: any;
}

export interface GoldMapping {
  id: string;
  gold: string;
  value: string;
  autogenerated?: boolean;
  isNewColumn?: boolean;
}

// ============================================================================
// Hierarchy Types
// ============================================================================

export interface HierarchyState {
  expandedConsumptionEntities: Set<string>;
  expandedCuratedEntities: Set<string>;
  visibleNodes: Set<string>;
}

export interface LayoutPosition {
  x: number;
  y: number;
}

export interface LayoutConfig {
  nodeWidth: number;
  nodeHeight: number;
  horizontalSpacing: number;
  verticalSpacing: number;
  columnWidth: number;
}

// ============================================================================
// Canvas State Types
// ============================================================================

export interface CanvasState {
  nodes: CanvasNode[];
  edges: CanvasEdge[];
  selectedNode: string | null;
  selectedEdge: string | null;
  hierarchyState?: HierarchyState;
}

export interface CanvasActions {
  addNode: (node: CanvasNode) => void;
  updateNode: (id: string, data: Partial<CanvasNodeData>) => void;
  deleteNode: (id: string) => void;
  addEdge: (edge: CanvasEdge) => void;
  updateEdge: (id: string, data: Partial<EdgeData>) => void;
  deleteEdge: (id: string) => void;
  selectNode: (id: string | null) => void;
  selectEdge: (id: string | null) => void;
  resetCanvas: () => void;
}

// ============================================================================
// File Data Types
// ============================================================================

export interface FileMetadata {
  key: string;
  fileName: string;
  location: string;
  size?: number;
  lastModified?: string;
  contentType?: string;
}

export interface ConsumptionFile {
  name: string;
  outputColumns: ColumnAttribute[];
  mode?: 'continuous' | 'triggered';
  environment?: 'development' | 'production';
  description?: string;
}

// ============================================================================
// API Response Types
// ============================================================================

export interface ColumnSchemaResponse {
  tableName: string;
  columns: ColumnAttribute[];
  primaryKeys?: string[];
  foreignKeys?: { column: string; references: string }[];
}

export interface MappingGenerationResponse {
  mappings: MappingRule[];
  confidence: number;
  suggestions?: string[];
}

// ============================================================================
// Component Props Types
// ============================================================================

export interface CanvasHeaderProps {
  title: string;
  subtitle?: string;
  onBack?: () => void;
  actions?: React.ReactNode;
}

export interface NodeComponentProps {
  id: string;
  data: CanvasNodeData;
  selected?: boolean;
  isConnectable?: boolean;
}

export interface EdgeComponentProps {
  id: string;
  sourceX: number;
  sourceY: number;
  targetX: number;
  targetY: number;
  sourcePosition?: string;
  targetPosition?: string;
  style?: React.CSSProperties;
  data?: EdgeData;
  selected?: boolean;
}

// ============================================================================
// Hook Return Types
// ============================================================================

export interface UseHierarchyManagerReturn {
  expandedConsumptionEntities: Set<string>;
  expandedCuratedEntities: Set<string>;
  toggleConsumptionEntity: (entityId: string) => void;
  toggleCuratedEntity: (entityId: string) => void;
  getVisibleNodes: (allNodes: CanvasNode[], edges: CanvasEdge[]) => CanvasNode[];
  calculateLayout: (nodes: CanvasNode[], config: LayoutConfig) => CanvasNode[];
}

export interface UseFieldMappingsReturn {
  generateMappings: (sourceColumns: string[], targetColumns: string[]) => MappingRule[];
  validateMapping: (mapping: MappingRule) => boolean;
  applyTransformation: (mapping: MappingRule, data: any) => any;
}

// ============================================================================
// Utility Function Types
// ============================================================================

export type NodePositionCalculator = (
  nodeIndex: number,
  totalNodes: number,
  columnX: number,
  config: LayoutConfig
) => LayoutPosition;

export type EdgePathGenerator = (
  sourceX: number,
  sourceY: number,
  targetX: number,
  targetY: number
) => string;

export type ColumnMatcher = (
  sourceColumn: string,
  targetColumns: string[]
) => { column: string; confidence: number } | null;
