import { useState, useEffect, useMemo } from "react";
import axios from "axios";
import curatedAi from "../assets/curatedAi-icon.svg";
import curatedFile from "../assets/curatedFile-icon.svg";
import aiIcon from "../assets/ai-icon.svg";
import {
  BiTrash,
  BiSpreadsheet,
  BiSolidCheckCircle,
  BiLockAlt,
  BiError,
  BiPencil,
  BiSave,
} from "react-icons/bi";
import {
  Button,
  Form,
  OverlayTrigger,
  Tooltip,
  Alert,
  Modal,
  Row,
  Col,
  Offcanvas,
  Image,
} from "react-bootstrap";
import LoadingOverlay from "../components/LoadingOverlay";
import PresenceIndicator from "../components/PresenceIndicator";
import CollaborationBanner from "../components/CollaborationBanner";
import { usePresence } from "../hooks/usePresence";

function EditEntityMappingsPage({
  entityName: propEntityName,
  curatedEntities: propCuratedEntities,
  fileData: propFileData,
}) {
  // Use prop if provided, otherwise fall back to URL param
  const entityName = propEntityName;

  // Get uploaded files data from props or fall back to location state
  const curatedEntities = propCuratedEntities || [];
  const fileData = propFileData || [];

  // Extract the entity name without the 'raw.' prefix
  const entityBaseName = entityName?.replace("raw.", "") || "";

  // Find the corresponding file data
  const currentFileData = fileData?.find(
    (file) =>
      file?.key
        ?.split("/")
        ?.pop()
        ?.replace(/\.[^/.]+$/, "") === entityBaseName
  );

  // Core data state
  const [rawAttributes, setRawAttributes] = useState([]);
  const [curatedAttributes, setCuratedAttributes] = useState([]);
  const [mappings, setMappings] = useState([]);
  const [curatedEntityName, setCuratedEntityName] = useState("");

  // UI state
  const [loading, setLoading] = useState(true);

  // Modal states
  const [actionModal, setActionModal] = useState({
    open: false,
    type: "",
    column: "",
    data: null,
  });
  const [descriptionModal, setDescriptionModal] = useState({
    open: false,
    column: "",
    description: "",
  });

  // Rules and transformations state
  const [columnRules, setColumnRules] = useState({});
  const [concatenationRules, setConcatenationRules] = useState([]);
  const [operatorRules, setOperatorRules] = useState({});
  const [entityNLPRules, setEntityNLPRules] = useState([]);

  // Column descriptions state
  const [columnDescriptions, setColumnDescriptions] = useState({});
  const [autoGeneratedDescriptions, setAutoGeneratedDescriptions] = useState(
    new Set()
  );
  const [savedNewColumns, setSavedNewColumns] = useState(new Set());

  // Collaborative presence tracking
  const flowId = useMemo(() => {
    return `entity-mapping-${entityName || 'unknown'}`;
  }, [entityName]);

  const { activeUsers, updateStatus } = usePresence('entity-mapping', flowId);
  const currentUserId = 'current-user-id'; // TODO: Get from auth context

  // Fetch schema from database
  useEffect(() => {
    async function fetchFileColumns() {
      const currentCuratedName =
        curatedEntities?.find(
          (entity) =>
            entity.startsWith("curated.") &&
            entity.replace("curated.", "") === entityBaseName
        ) || `curated.${entityBaseName}`;
      setCuratedEntityName(currentCuratedName);

      try {
        const schemaResponse = await axios.get(
          `/api/raw-schemas/${encodeURIComponent(entityName)}`
        );

        if (schemaResponse.data.success && schemaResponse.data.schema) {
          const schema = schemaResponse.data.schema;
          const schemaAttributes = schema.schemaAttributes || [];

          if (schemaAttributes.length === 0) {
            alert(
              "Schema found but no columns were extracted. Please re-upload the file."
            );
            setLoading(false);
            return;
          }

          const columns = schemaAttributes.map((attr) =>
            typeof attr === "string" ? attr : attr.name
          );

          setRawAttributes(columns);

          const curatedCols = [
            ...columns,
            "updated_at",
            "version",
            "is_deleted",
          ];
          setCuratedAttributes(curatedCols);

          // Fetch column metadata (datatypes and descriptions) from backend
          try {
            const metadataResponse = await axios.get(
              `/api/raw-schemas/${encodeURIComponent(
                entityName
              )}/column-metadata`
            );

            if (
              metadataResponse.data.success &&
              metadataResponse.data.columnMetadata
            ) {
              const columnMetadata = metadataResponse.data.columnMetadata;

              const descriptions = {};
              const autoGenerated = new Set();
              columnMetadata.forEach((metadata) => {
                descriptions[metadata.columnName] = metadata.description;
                if (metadata.isGenerated) {
                  autoGenerated.add(metadata.columnName);
                }
              });

              setColumnDescriptions(descriptions);
              setAutoGeneratedDescriptions(autoGenerated);
            }
          } catch (metadataError) {
            console.warn(
              "Failed to fetch column metadata, using default descriptions:",
              metadataError
            );
            // Continue without metadata - descriptions will be empty
            // Set empty descriptions to avoid undefined errors
            setColumnDescriptions({});
            setAutoGeneratedDescriptions(new Set());
          }

          // Create initial mappings
          setMappings(createInitialMappings(columns, curatedCols));
        } else {
          alert(
            "No schema found for this entity. Please ensure the entity has been properly uploaded and processed."
          );
          setLoading(false);
          return;
        }
      } catch (err) {
        alert(
          "Failed to load schema from database. Please ensure the entity has been properly uploaded and processed."
        );
        setLoading(false);
        return;
      }

      setLoading(false);
    }

    fetchFileColumns();
  }, [currentFileData, entityName]);

  // Load previously saved transformations
  useEffect(() => {
    async function loadSavedTransformations() {
      if (!entityName) return;

      try {
        const response = await axios.get(
          `/api/transformations/${encodeURIComponent(entityName)}`
        );

        if (response.data && response.data.transformations) {
          const savedTransformations = response.data.transformations;

          if (savedTransformations.mappings) {
            setMappings(savedTransformations.mappings);
          }

          if (savedTransformations.columnRules) {
            setColumnRules(savedTransformations.columnRules);
          }

          if (savedTransformations.operatorRules) {
            setOperatorRules(savedTransformations.operatorRules);
          }

          // Load saved concatenation rules
          if (savedTransformations.concatenationRules) {
            setConcatenationRules(savedTransformations.concatenationRules);
          }

          if (savedTransformations.entityNLPRules) {
            setEntityNLPRules(savedTransformations.entityNLPRules);
          }

          if (savedTransformations.columnDescriptions) {
            const mergedDescriptions = {
              ...columnDescriptions,
              ...savedTransformations.columnDescriptions,
            };
            setColumnDescriptions(mergedDescriptions);

            const updatedAutoGenerated = new Set(autoGeneratedDescriptions);
            Object.keys(savedTransformations.columnDescriptions).forEach(
              (column) => {
                updatedAutoGenerated.delete(column);
              }
            );
            setAutoGeneratedDescriptions(updatedAutoGenerated);
          }

          if (savedTransformations.mappings) {
            const existingNewColumns = savedTransformations.mappings
              .filter(
                (mapping) => mapping.isNewColumn && mapping.curated.trim()
              )
              .map((mapping) => mapping.curated.trim());
            setSavedNewColumns(new Set(existingNewColumns));
          }

          if (savedTransformations.curatedEntityName) {
            setCuratedEntityName(savedTransformations.curatedEntityName);
          }

          if (savedTransformations.curatedAttributes) {
            setCuratedAttributes(savedTransformations.curatedAttributes);
          }
        }
      } catch (error) {
        // Normal if no transformations have been saved yet
      }
    }

    if (!loading && rawAttributes.length > 0) {
      loadSavedTransformations();
    }
  }, [entityName, loading, rawAttributes.length]);

  // Initialize control column descriptions when component loads
  useEffect(() => {
    if (!loading && curatedAttributes.length > 0) {
      const controlColumns = [
        "_ingest_timestamp",
        "_source_system",
        "_record_status",
        "_update_timestamp",
        "_batch_id",
        "_created_by",
        "_updated_by",
      ];

      setColumnDescriptions((prev) => {
        const updated = { ...prev };
        let hasChanges = false;

        controlColumns.forEach((column) => {
          if (!updated[column]) {
            updated[column] = getControlColumnDescription(column);
            hasChanges = true;
          }
        });

        return hasChanges ? updated : prev;
      });
    }
  }, [loading, curatedAttributes.length]);

  // Create initial mappings based on actual file columns
  const createInitialMappings = (rawCols, curatedCols) => {
    const safeRawCols = Array.isArray(rawCols) ? rawCols : [];
    const safeCuratedCols = Array.isArray(curatedCols) ? curatedCols : [];

    const rawMappings = safeRawCols.map((rawAttr) => {
      const matchingCurated = safeCuratedCols?.find(
        (curatedAttr) =>
          curatedAttr.toLowerCase().includes(rawAttr.toLowerCase()) ||
          rawAttr.toLowerCase().includes(curatedAttr.toLowerCase())
      );

      return {
        raw: rawAttr,
        curated: matchingCurated || rawAttr,
        autogenerated: true,
      };
    });

    const controlColumns = [
      "_ingest_timestamp",
      "_source_system",
      "_record_status",
      "_update_timestamp",
      "_batch_id",
      "_created_by",
      "_updated_by",
    ];

    const controlMappings = controlColumns.map((controlCol) => ({
      raw: "",
      curated: controlCol,
      autogenerated: true,
      isControlColumn: true,
      isEntityLevel: true,
    }));

    return [...rawMappings, ...controlMappings];
  };

  const isControlColumn = (columnName) => {
    const controlColumns = [
      "_ingest_timestamp",
      "_source_system",
      "_record_status",
      "_update_timestamp",
      "_batch_id",
      "_created_by",
      "_updated_by",
    ];
    return controlColumns.includes(columnName);
  };

  const getControlColumnDescription = (columnName) => {
    const descriptions = {
      _ingest_timestamp:
        "Records when data was ingested into the system. Automatically populated by the data pipeline.",
      _source_system:
        "Identifies the source system that provided the data. Used for data lineage tracking.",
      _record_status:
        "Status after validation (valid/quarantined/error). Indicates data quality assessment.",
      _update_timestamp:
        "Last update time in the silver/curated layer. Tracks when the record was last modified.",
      _batch_id:
        "Associates records with a specific processing batch. Used for batch processing and error tracking.",
      _created_by:
        "Process or user that created the record. Tracks data origin and responsibility.",
      _updated_by:
        "Process or user that last updated the record. Maintains audit trail of changes.",
    };
    return descriptions[columnName] || "";
  };

  // Update mapping
  const updateMapping = async (idx, field, value) => {
    // Prevent changing to control column names
    if (field === "curated") {
      const controlColumns = [
        "_ingest_timestamp",
        "_source_system",
        "_record_status",
        "_update_timestamp",
        "_batch_id",
        "_created_by",
        "_updated_by",
      ];

      if (controlColumns.includes(value)) {
        alert(
          "Cannot use a control column name. Control columns are reserved for system use."
        );
        return;
      }
    }

    const updatedMappings = mappings.map((row, i) =>
      i === idx ? { ...row, [field]: value, autogenerated: false } : row
    );
    setMappings(updatedMappings);

    // Auto-save mappings after update (but not for new columns until they have a name)
    if (
      field === "curated" &&
      value.trim() &&
      !updatedMappings[idx].isNewColumn
    ) {
      await autoSaveMappings(updatedMappings, columnDescriptions);
    }
  };

  // Delete mapping
  const deleteMapping = async (idx) => {
    // Prevent deletion of control columns
    if (mappings?.[idx]?.isControlColumn) {
      alert(
        "Control columns cannot be deleted as they are required for data lineage and auditability."
      );
      return;
    }

    const updatedMappings = mappings?.filter((_, i) => i !== idx) || [];
    setMappings(updatedMappings);

    // Auto-save mappings after deletion
    await autoSaveMappings(updatedMappings, columnDescriptions);
  };

  const addMapping = () => {
    setMappings((m) => {
      const currentMappings = Array.isArray(m) ? m : [];
      return [
        ...currentMappings,
        {
          raw: "",
          curated: "",
          autogenerated: false,
          isNewColumn: true,
        },
      ];
    });
  };

  const saveNewColumn = async (idx) => {
    const mapping = mappings[idx];
    if (!mapping.curated.trim()) {
      alert("Please enter a column name before saving.");
      return;
    }

    const controlColumns = [
      "_ingest_timestamp",
      "_source_system",
      "_record_status",
      "_update_timestamp",
      "_batch_id",
      "_created_by",
      "_updated_by",
    ];

    if (controlColumns.includes(mapping.curated.trim())) {
      alert(
        "Cannot use a control column name. Control columns are reserved for system use."
      );
      return;
    }

    try {
      // Update the mapping to ensure it's properly saved
      const updatedMappings = mappings.map((row, i) =>
        i === idx
          ? {
              ...row,
              isNewColumn: true, // Keep as new column for proper rendering
              curated: row.curated.trim(), // Ensure trimmed value
              autogenerated: false,
            }
          : row
      );

      // Update state first
      setMappings(updatedMappings);

      // Auto-save the mappings with the updated mappings
      const newColumnName = mapping.curated.trim();
      await autoSaveMappings(
        updatedMappings,
        columnDescriptions,
        newColumnName
      );

      // Mark this column as saved
      setSavedNewColumns((prev) => new Set([...prev, newColumnName]));
    } catch (error) {}
  };

  const [showDescModal, setShowDescModal] = useState(false);

  // Action handlers for column modifications
  const handleColumnRename = (columnName) => {
    setActionModal({
      open: true,
      type: "rename",
      column: columnName,
      data: { newName: "" },
    });
  };

  const handleSaveAction = () => {
    const { type, column, data } = actionModal;

    switch (type) {
      case "rename":
        // Update the column name in curated attributes (not raw)
        // Prevent renaming to control column names
        const reservedControlColumns = [
          "_ingest_timestamp",
          "_source_system",
          "_record_status",
          "_update_timestamp",
          "_batch_id",
          "_created_by",
          "_updated_by",
        ];

        if (reservedControlColumns.includes(data.newName)) {
          alert(
            "Cannot rename to a control column name. Control columns are reserved for system use."
          );
          return;
        }

        const newCuratedAttributes = curatedAttributes.map((attr) =>
          attr === column ? data.newName : attr
        );
        setCuratedAttributes(newCuratedAttributes);

        // Update mappings to use the new curated column name
        setMappings((prev) =>
          prev.map((mapping) =>
            mapping.curated === column
              ? { ...mapping, curated: data.newName }
              : mapping
          )
        );
        break;

        // Add concatenation rule
        // Prevent creating target columns with control column names
        const systemControlColumns = [
          "_ingest_timestamp",
          "_source_system",
          "_record_status",
          "_update_timestamp",
          "_batch_id",
          "_created_by",
          "_updated_by",
        ];

        if (systemControlColumns.includes(data.targetColumn)) {
          alert(
            "Cannot create a concatenation target with a control column name. Control columns are reserved for system use."
          );
          return;
        }

        setConcatenationRules((prev) => [
          ...prev,
          {
            id: Date.now(),
            sourceColumns: data.sourceColumns,
            targetColumn: data.targetColumn,
            separator: data.separator,
          },
        ]);
        break;
    }

    setActionModal({ open: false, type: "", column: "", data: null });
  };

  const handleColumnDescription = (columnName) => {
    setDescriptionModal({
      open: true,
      column: columnName,
      description: columnDescriptions[columnName] || "",
    });
    setShowDescModal(true);
  };

  const saveColumnDescription = async () => {
    // Prevent saving descriptions for control columns
    if (isControlColumn(descriptionModal.column)) {
      alert(
        "Control column descriptions are system-defined and cannot be modified."
      );
      return;
    }

    if (descriptionModal.column && descriptionModal.description.trim()) {
      const updatedColumnDescriptions = {
        ...columnDescriptions,
        [descriptionModal.column]: descriptionModal.description.trim(),
      };
      setColumnDescriptions(updatedColumnDescriptions);

      // Mark this description as user-edited (remove from auto-generated set)
      const updatedAutoGenerated = new Set(autoGeneratedDescriptions);
      updatedAutoGenerated.delete(descriptionModal.column);
      setAutoGeneratedDescriptions(updatedAutoGenerated);

      setDescriptionModal({ open: false, column: "", description: "" });

      // Auto-save mappings after description update
      await autoSaveMappings(mappings, updatedColumnDescriptions);
    } else {
      alert("Please enter a description for the column.");
    }
  };

  // Auto-save function for mappings
  const autoSaveMappings = async (
    currentMappings = mappings,
    currentColumnDescriptions = columnDescriptions,
    newlySavedColumn = null
  ) => {
    try {
      // Collect new columns from mappings (excluding control columns)
      // Include both columns with isNewColumn flag and columns that were just saved
      const newColumns = currentMappings
        .filter(
          (mapping) =>
            mapping.curated.trim() &&
            !mapping.isControlColumn &&
            (mapping.isNewColumn ||
              // Include columns that were just saved (have no raw mapping but have curated name)
              (!mapping.raw && mapping.curated.trim()) ||
              // Include the specific column that was just saved
              (newlySavedColumn && mapping.curated === newlySavedColumn))
        )
        .map((mapping) => mapping.curated.trim());

      // Add new columns to curated attributes if they don't exist (excluding control columns)
      const updatedCuratedAttributes = [...curatedAttributes];
      newColumns.forEach((column) => {
        if (!updatedCuratedAttributes.includes(column)) {
          updatedCuratedAttributes.push(column);
        }
      });

      // Collect control columns for entity-level metadata
      const controlColumns = currentMappings
        .filter((mapping) => mapping.isControlColumn)
        .map((mapping) => mapping.curated);

      // Collect all transformations for this entity
      const transformations = {
        entityName: entityName,
        curatedEntityName: curatedEntityName,
        rawAttributes: rawAttributes,
        curatedAttributes: updatedCuratedAttributes,
        mappings: currentMappings,
        columnRules: columnRules,
        operatorRules: operatorRules,
        concatenationRules: concatenationRules,
        entityNLPRules: entityNLPRules,
        columnDescriptions: currentColumnDescriptions,
        fileData: currentFileData,
        newColumns: newColumns,
        entityLevelMetadata: {
          controlColumns: controlColumns,
          controlColumnsCount: controlColumns.length,
          note: "Control columns are preserved in mappings for data lineage but not included in curated file",
        },
      };

      // Save transformations to backend (only save, don't generate file)
      await axios.post("/api/transformations/save", {
        entityName: entityName,
        transformations: transformations,
      });
    } catch (error) {}
  };

  if (loading) {
    return <LoadingOverlay text="Loading file columns..." />;
  }

  return (
    <>
      {/* Collaborative editing presence */}
      <div style={{ marginBottom: '16px', display: 'flex', gap: '12px', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ flex: 1 }}>
          <CollaborationBanner
            activeUsers={activeUsers}
            currentUserId={currentUserId}
            onRefresh={() => window.location.reload()}
          />
        </div>
        <PresenceIndicator
          activeUsers={activeUsers}
          currentUserId={currentUserId}
          maxVisible={5}
          showCount={true}
        />
      </div>

      {/* Mappings Table */}
      <div className="bg-light rounded p-3">
        {mappings.map((row, idx) => (
          <Row key={idx} className="mb-2 align-items-center">
            <Col md={4}>
              {row.isNewColumn ? (
                <span>New Column</span>
              ) : row.isControlColumn ? (
                <span className="d-inline-flex gap-2 align-items-center">
                  <BiLockAlt /> Entity Metadata
                </span>
              ) : (
                <Form.Select
                  size="sm"
                  value={row.raw}
                  onChange={(e) => updateMapping(idx, "raw", e.target.value)}
                >
                  {rawAttributes.map((attr) => (
                    <option key={attr} value={attr}>
                      {attr}
                    </option>
                  ))}
                </Form.Select>
              )}
            </Col>

            <Col md={{ span: 4, offset: 2 }}>
              <div className="d-flex gap-2">
                {row.isNewColumn ? (
                  <div className="d-flex gap-2 align-items-center w-100">
                    <Form.Control
                      type="text"
                      size="sm"
                      value={row.curated}
                      onChange={(e) =>
                        updateMapping(idx, "curated", e.target.value)
                      }
                      placeholder="Enter new column name"
                    />
                    {!savedNewColumns.has(row.curated.trim()) && (
                      <Button
                        variant="primary btn-icon"
                        size="sm"
                        onClick={() => saveNewColumn(idx)}
                        disabled={!row.curated.trim()}
                        title="Save new column"
                      >
                        <BiSave />
                      </Button>
                    )}
                    {savedNewColumns.has(row.curated.trim()) && (
                      <span className="text-success" title="Column saved">
                        ✅
                      </span>
                    )}
                  </div>
                ) : row.isControlColumn ? (
                  <div className="alert alert-primary p-2 w-100 m-0">
                    {row.curated} (entity-level)
                  </div>
                ) : (
                  <Form.Select
                    size="sm"
                    value={row.curated}
                    onChange={(e) =>
                      updateMapping(idx, "curated", e.target.value)
                    }
                  >
                    {curatedAttributes.map((attr) => (
                      <option key={attr} value={attr}>
                        {attr}
                      </option>
                    ))}
                  </Form.Select>
                )}

                <div className="d-flex justify-content-start">
                  <OverlayTrigger
                    placement="left"
                    overlay={<Tooltip>Auto Generated</Tooltip>}
                  >
                    <Button
                      style={{
                        display: row.autogenerated ? "inline-block" : "none",
                      }}
                      variant="default text-success btn-icon"
                      size="sm"
                    >
                      <BiSolidCheckCircle size={20} />
                    </Button>
                  </OverlayTrigger>

                  <OverlayTrigger
                    placement="left"
                    overlay={
                      <Tooltip>Entity-Level Metadata (Non-editable)</Tooltip>
                    }
                  >
                    <Button
                      style={{
                        display: row.isControlColumn ? "inline-block" : "none",
                      }}
                      variant="default btn-icon"
                      size="sm"
                    >
                      <BiLockAlt size={20} />
                    </Button>
                  </OverlayTrigger>
                  <OverlayTrigger
                    placement="left"
                    overlay={
                      <Tooltip>
                        {autoGeneratedDescriptions.has(row.curated)
                          ? "Auto-generated description (click to edit)"
                          : "Has description"}
                      </Tooltip>
                    }
                  >
                    <Button
                      style={{
                        display:
                          columnDescriptions[row.curated] ||
                          isControlColumn(row.curated)
                            ? "inline-block"
                            : "none",
                        position: "relative",
                      }}
                      variant="default btn-icon"
                      size="sm"
                    >
                      <BiSpreadsheet size={20} />
                      {autoGeneratedDescriptions.has(row.curated) && (
                        <span
                          style={{
                            position: "absolute",
                            top: "-2px",
                            right: "-2px",
                            background: "#28a745",
                            color: "white",
                            borderRadius: "50%",
                            width: "12px",
                            height: "12px",
                            fontSize: "8px",
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                          }}
                          title="Auto-generated"
                        >
                          A
                        </span>
                      )}
                    </Button>
                  </OverlayTrigger>
                </div>
              </div>
            </Col>

            <Col md={2}>
              <div className="d-flex gap-2 justify-content-end">
                {row.isNewColumn ? (
                  <>
                    <OverlayTrigger
                      placement="top"
                      overlay={<Tooltip>Add/edit column description</Tooltip>}
                    >
                      <Button
                        variant="outline-secondary btn-icon"
                        size="sm"
                        onClick={() => handleColumnDescription(row.curated)}
                        disabled={!row.curated.trim()}
                      >
                        <BiSpreadsheet />
                      </Button>
                    </OverlayTrigger>
                  </>
                ) : row.isControlColumn ? (
                  <OverlayTrigger
                    placement="top"
                    overlay={<Tooltip>Add/edit column description</Tooltip>}
                  >
                    <Button
                      variant="outline-secondary btn-icon"
                      size="sm"
                      onClick={() => handleColumnDescription(row.curated)}
                      disabled={!row.curated.trim()}
                    >
                      <BiSpreadsheet />
                    </Button>
                  </OverlayTrigger>
                ) : (
                  <>
                    <OverlayTrigger
                      placement="top"
                      overlay={<Tooltip>Rename curated column</Tooltip>}
                    >
                      <Button
                        variant="outline-secondary btn-icon"
                        size="sm"
                        onClick={() => handleColumnRename(row.curated)}
                        disabled={isControlColumn(row.curated)}
                      >
                        <BiPencil />
                      </Button>
                    </OverlayTrigger>

                    <OverlayTrigger
                      placement="top"
                      overlay={<Tooltip>Add/edit column description</Tooltip>}
                    >
                      <Button
                        variant="outline-secondary btn-icon"
                        size="sm"
                        onClick={() => handleColumnDescription(row.curated)}
                        disabled={isControlColumn(row.curated)}
                      >
                        <BiSpreadsheet />
                      </Button>
                    </OverlayTrigger>
                  </>
                )}
                {!row.isControlColumn && (
                  <OverlayTrigger
                    placement="top"
                    overlay={<Tooltip>Delete</Tooltip>}
                  >
                    <Button
                      variant="outline-secondary btn-icon"
                      size="sm"
                      onClick={() => deleteMapping(idx)}
                    >
                      <BiTrash />
                    </Button>
                  </OverlayTrigger>
                )}
              </div>
            </Col>
          </Row>
        ))}

        <Row>
          <Col md={{ span: 4, offset: 6 }} className="d-flex gap-2">
            <Button variant="link" className="ps-0" onClick={addMapping}>
              + Add New Attribute
            </Button>
          </Col>
        </Row>
      </div>

      {/* Action Modal now only used for renaming column*/}
      {actionModal.open && (
        <Modal
          show={actionModal.open}
          onHide={() =>
            setActionModal({ open: false, type: "", column: "", data: null })
          }
          centered
          backdrop="static"
        >
          <Modal.Header closeButton>
            <Modal.Title>
              {actionModal.type === "rename" && "Rename Curated Column"}
            </Modal.Title>
          </Modal.Header>

          <Modal.Body>
            {/* Rename Column */}
            {actionModal.type === "rename" && (
              <>
                <Form.Group className="mb-4">
                  <Form.Label>
                    <span className="text-muted">Rename curated column:</span>{" "}
                    <strong>{actionModal.column}</strong>
                  </Form.Label>

                  <Form.Control
                    type="text"
                    placeholder="New curated column name"
                    value={actionModal.data.newName}
                    onChange={(e) =>
                      setActionModal((prev) => ({
                        ...prev,
                        data: { ...prev.data, newName: e.target.value },
                      }))
                    }
                  />
                </Form.Group>
              </>
            )}
          </Modal.Body>

          <Modal.Footer>
            <Button
              variant="outline-secondary"
              onClick={() =>
                setActionModal({
                  open: false,
                  type: "",
                  column: "",
                  data: null,
                })
              }
            >
              Cancel
            </Button>
            <Button variant="primary" onClick={handleSaveAction}>
              Save
            </Button>
          </Modal.Footer>
        </Modal>
      )}

      {/* Description Modal */}
      {descriptionModal.open && (
        <Offcanvas
          backdrop="static"
          show={showDescModal}
          onHide={() => setShowDescModal(false)}
          placement="end"
        >
          <Offcanvas.Header closeButton>
            <Offcanvas.Title>Column Description</Offcanvas.Title>
            <div className="d-flex align-items-center gap-2">
              <Image src={curatedFile} alt="" />
              <span>{entityName}</span>
              <Image src={curatedAi} alt="" />
              <Image src={curatedFile} alt="" />
              <span>{entityName}</span>
            </div>
          </Offcanvas.Header>

          <Offcanvas.Body>
            <Form.Group className="mb-3">
              <Form.Label>Column:</Form.Label>
              <Form.Select
                value={descriptionModal.column}
                onChange={(e) => {
                  const selectedColumn = e.target.value;
                  let description = "";

                  if (selectedColumn) {
                    if (isControlColumn(selectedColumn)) {
                      description = getControlColumnDescription(selectedColumn);
                    } else {
                      description = columnDescriptions[selectedColumn] || "";
                    }
                  }

                  setDescriptionModal((prev) => ({
                    ...prev,
                    column: selectedColumn,
                    description: description,
                  }));
                }}
              >
                <option value="">Select a column to edit description</option>
                {curatedAttributes.map((attr) => (
                  <option key={attr} value={attr}>
                    {attr}{" "}
                    {isControlColumn(attr)
                      ? "(system)"
                      : autoGeneratedDescriptions.has(attr)
                      ? "(auto-generated)"
                      : columnDescriptions[attr]
                      ? "(has description)"
                      : ""}
                  </option>
                ))}
              </Form.Select>
            </Form.Group>

            <Form.Group className="mb-3">
              <Form.Label>
                Description:
                {autoGeneratedDescriptions.has(descriptionModal.column) && (
                  <span
                    className="ms-2 badge bg-success"
                    style={{ fontSize: "0.75rem" }}
                  >
                    Auto-generated
                  </span>
                )}
              </Form.Label>

              <div className="gradient-textarea">
                <Form.Control
                  as="textarea"
                  value={descriptionModal.description}
                  onChange={(e) =>
                    setDescriptionModal((prev) => ({
                      ...prev,
                      description: e.target.value,
                    }))
                  }
                  placeholder={
                    isControlColumn(descriptionModal.column)
                      ? "System-defined description (read-only)"
                      : "Enter column description..."
                  }
                  disabled={isControlColumn(descriptionModal.column)}
                />
                <div className="ai-icon">
                  <Image src={aiIcon} alt="" width={30} />
                </div>
              </div>

              {isControlColumn(descriptionModal.column) && (
                <Alert variant="warning mt-3">
                  <div className="alert-icon">
                    <BiError size={30} />
                  </div>
                  <div className="alert-text">
                    This is a system-defined control column. Descriptions cannot
                    be modified.
                  </div>
                </Alert>
              )}
            </Form.Group>
            {!isControlColumn(descriptionModal.column) && (
              <div className="text-end">
                <Button variant="primary" onClick={saveColumnDescription}>
                  Save & Submit
                </Button>
              </div>
            )}
          </Offcanvas.Body>
        </Offcanvas>
      )}
    </>
  );
}

export default EditEntityMappingsPage;
