import { useNavigate, useLocation } from "react-router-dom";
import { useState, useEffect, useMemo } from "react";
import axios from "axios";
import ColumnETLModal from "../components/ColumnETLModal";
import PresenceIndicator from "../components/PresenceIndicator";
import CollaborationBanner from "../components/CollaborationBanner";
import { usePresence } from "../hooks/usePresence";
import curatedAi from "../assets/curatedAi-icon.svg";
import curatedFile from "../assets/curatedFile-icon.svg";
import aiIcon from "../assets/ai-icon.svg";
import {
  BiColumns,
  BiSync,
  BiRadioCircleMarked,
  BiPencil,
  BiTrash,
  BiSolidError,
  BiRefresh,
  BiCheckDouble,
  BiSpreadsheet,
  BiSolidBolt,
  BiBulb,
  BiSolidCheckCircle,
  BiSearch,
  BiInfoCircle,
  BiCopyAlt,
  BiSolidXCircle,
  BiDownload,
} from "react-icons/bi";
import {
  Button,
  Form,
  Modal,
  Table,
  OverlayTrigger,
  Tooltip,
  Alert,
  Badge,
  Row,
  Col,
  Offcanvas,
  Image,
} from "react-bootstrap";

function EditConsumptionEntityMappingsPage({
  entityName: propEntityName,
  consumptionData: propConsumptionData,
  records: propRecords,
  onSwitchToCanvas,
}) {
  // const params = useParams();
  const location = useLocation();
  const navigate = useNavigate();

  // Use prop if provided, otherwise fall back to useParams for backward compatibility
  const entityName = propEntityName || params.entityName;

  // Use real data if passed from navigation or props
  const records = propRecords || location.state?.records || [];
  const outputColumns = location.state?.outputColumns || [];

  // Derive attributes from outputColumns or records
  const attributes = outputColumns.length
    ? outputColumns.map((col) => col.name)
    : records[0]
    ? Object.keys(records[0])
    : [];

  // Set up mappings state
  const [mappings, setMappings] = useState(
    attributes.length > 0
      ? attributes.map((attr) => ({
          gold: attr,
          value: attr,
          autogenerated: true,
        }))
      : [
          // fallback mock mapping if nothing is available
          { gold: "id", value: "id", autogenerated: true },
        ]
  );

  // State for schema data types and descriptions
  const [schemaDataTypes, setSchemaDataTypes] = useState({});
  const [schemaDescriptions, setSchemaDescriptions] = useState({});

  // Collaborative presence tracking
  const flowId = useMemo(() => {
    return `gold-entity-mapping-${entityName || 'unknown'}`;
  }, [entityName]);

  const { activeUsers, updateStatus } = usePresence('entity-mapping', flowId);
  const currentUserId = 'current-user-id'; // TODO: Get from auth context

  // LLM-like data type generation function (simulates LLM service)
  const generateLLMDataType = (columnName, sampleData) => {
    console.log(`Generating data type for column: ${columnName}`);
    const name = columnName.toLowerCase();

    // Enhanced pattern-based data type detection (simulating LLM analysis)
    if (name.includes("id") || name.endsWith("_id")) {
      console.log(`Column ${columnName} detected as ID - returning integer`);
      return { type: "integer", nullable: false };
    }
    if (name.includes("email") || name.includes("mail")) {
      console.log(`Column ${columnName} detected as email - returning string`);
      return { type: "string", nullable: true };
    }
    if (
      name.includes("phone") ||
      name.includes("mobile") ||
      name.includes("tel")
    ) {
      console.log(`Column ${columnName} detected as phone - returning string`);
      return { type: "string", nullable: true };
    }
    if (
      name.includes("amount") ||
      name.includes("price") ||
      name.includes("cost") ||
      name.includes("total")
    ) {
      console.log(
        `Column ${columnName} detected as monetary - returning decimal`
      );
      return { type: "decimal", nullable: true };
    }
    if (
      name.includes("quantity") ||
      name.includes("count") ||
      name.includes("number")
    ) {
      console.log(
        `Column ${columnName} detected as quantity - returning integer`
      );
      return { type: "integer", nullable: true };
    }
    if (
      name.includes("date") ||
      name.includes("created") ||
      name.includes("updated") ||
      name.includes("timestamp")
    ) {
      console.log(`Column ${columnName} detected as date - returning datetime`);
      return { type: "datetime", nullable: true };
    }
    if (
      name.includes("is_") ||
      name.includes("has_") ||
      name.includes("active") ||
      name.includes("enabled")
    ) {
      console.log(
        `Column ${columnName} detected as boolean - returning boolean`
      );
      return { type: "boolean", nullable: true };
    }
    if (
      name.includes("url") ||
      name.includes("link") ||
      name.includes("website")
    ) {
      console.log(`Column ${columnName} detected as URL - returning string`);
      return { type: "string", nullable: true };
    }
    if (
      name.includes("address") ||
      name.includes("location") ||
      name.includes("city") ||
      name.includes("country")
    ) {
      console.log(
        `Column ${columnName} detected as location - returning string`
      );
      return { type: "string", nullable: true };
    }
    if (
      name.includes("description") ||
      name.includes("notes") ||
      name.includes("comment")
    ) {
      console.log(
        `Column ${columnName} detected as description - returning string`
      );
      return { type: "string", nullable: true };
    }
    if (
      name.includes("name") ||
      name.includes("title") ||
      name.includes("label")
    ) {
      console.log(
        `Column ${columnName} detected as name/title - returning string`
      );
      return { type: "string", nullable: true };
    }
    if (
      name.includes("status") ||
      name.includes("state") ||
      name.includes("type") ||
      name.includes("category")
    ) {
      console.log(`Column ${columnName} detected as status - returning string`);
      return { type: "string", nullable: true };
    }

    // If we have sample data, analyze it for better detection
    if (sampleData && sampleData.length > 0) {
      const columnValues = sampleData
        .slice(0, Math.min(100, sampleData.length))
        .map((row) => row[columnName])
        .filter((val) => val !== undefined && val !== null);

      if (columnValues.length > 0) {
        const sampleValue = columnValues[0];
        if (typeof sampleValue === "number") {
          const type = Number.isInteger(sampleValue) ? "integer" : "decimal";
          console.log(
            `Column ${columnName} analyzed from sample data - returning ${type}`
          );
          return {
            type: type,
            nullable: columnValues.some(
              (val) => val === null || val === undefined
            ),
          };
        } else if (typeof sampleValue === "boolean") {
          console.log(
            `Column ${columnName} analyzed from sample data - returning boolean`
          );
          return {
            type: "boolean",
            nullable: columnValues.some(
              (val) => val === null || val === undefined
            ),
          };
        } else if (
          sampleValue instanceof Date ||
          !isNaN(Date.parse(sampleValue))
        ) {
          console.log(
            `Column ${columnName} analyzed from sample data - returning datetime`
          );
          return {
            type: "datetime",
            nullable: columnValues.some(
              (val) => val === null || val === undefined
            ),
          };
        }
      }
    }

    // Default fallback
    console.log(
      `Column ${columnName} using default fallback - returning string`
    );
    return { type: "string", nullable: true };
  };

  // LLM-like description generation function (simulates LLM service)
  const generateLLMDescription = (columnName, dataTypeInfo, entityName) => {
    console.log(
      `Generating description for column: ${columnName}, entity: ${entityName}`
    );
    const name = columnName.toLowerCase();
    const entity = entityName ? entityName.toLowerCase() : "";

    // Enhanced context-aware description generation (simulating LLM analysis)
    if (name.includes("id") || name.endsWith("_id")) {
      const entityType = name.replace(/_id$/, "").replace(/_/g, " ");
      const description = `Unique identifier for the ${entityType} in the ${entity} dataset`;
      console.log(`Generated ID description: ${description}`);
      return description;
    }
    if (name.includes("email") || name.includes("mail")) {
      const description = `Email address for the ${entity} record, used for communication and identification`;
      console.log(`Generated email description: ${description}`);
      return description;
    }
    if (
      name.includes("phone") ||
      name.includes("mobile") ||
      name.includes("tel")
    ) {
      const description = `Contact phone number for the ${entity} record`;
      console.log(`Generated phone description: ${description}`);
      return description;
    }
    if (
      name.includes("amount") ||
      name.includes("price") ||
      name.includes("cost")
    ) {
      const description = `Monetary value representing the ${name.replace(
        /_/g,
        " "
      )} for this ${entity} record`;
      console.log(`Generated amount description: ${description}`);
      return description;
    }
    if (name.includes("total")) {
      const description = `Total calculated value for this ${entity} record`;
      console.log(`Generated total description: ${description}`);
      return description;
    }
    if (name.includes("quantity") || name.includes("count")) {
      const description = `Numeric count or quantity value for the ${name.replace(
        /_/g,
        " "
      )}`;
      console.log(`Generated quantity description: ${description}`);
      return description;
    }
    if (name.includes("number")) {
      const description = `Numeric identifier or reference number for this ${entity} record`;
      console.log(`Generated number description: ${description}`);
      return description;
    }
    if (name.includes("created") || name.includes("created_at")) {
      const description = `Timestamp indicating when this ${entity} record was first created in the system`;
      console.log(`Generated created description: ${description}`);
      return description;
    }
    if (name.includes("updated") || name.includes("updated_at")) {
      const description = `Timestamp indicating when this ${entity} record was last modified`;
      console.log(`Generated updated description: ${description}`);
      return description;
    }
    if (name.includes("date")) {
      const description = `Date information associated with this ${entity} record`;
      console.log(`Generated date description: ${description}`);
      return description;
    }
    if (name.includes("timestamp")) {
      const description = `Precise timestamp for when this ${entity} record was processed or recorded`;
      console.log(`Generated timestamp description: ${description}`);
      return description;
    }
    if (name.includes("is_") || name.includes("has_")) {
      const flag = name.replace(/^is_|has_/, "").replace(/_/g, " ");
      const description = `Boolean flag indicating whether this ${entity} record ${flag}`;
      console.log(`Generated boolean flag description: ${description}`);
      return description;
    }
    if (name.includes("active") || name.includes("enabled")) {
      const description = `Boolean flag indicating whether this ${entity} record is currently active or enabled`;
      console.log(`Generated active description: ${description}`);
      return description;
    }
    if (name.includes("url") || name.includes("link")) {
      const description = `Web URL or link associated with this ${entity} record`;
      console.log(`Generated URL description: ${description}`);
      return description;
    }
    if (name.includes("website")) {
      const description = `Website URL for this ${entity} record`;
      console.log(`Generated website description: ${description}`);
      return description;
    }
    if (name.includes("address")) {
      const description = `Physical address information for this ${entity} record`;
      console.log(`Generated address description: ${description}`);
      return description;
    }
    if (
      name.includes("location") ||
      name.includes("city") ||
      name.includes("country")
    ) {
      const description = `Geographic location information for this ${entity} record`;
      console.log(`Generated location description: ${description}`);
      return description;
    }
    if (name.includes("description") || name.includes("notes")) {
      const description = `Detailed description or notes providing additional context about this ${entity} record`;
      console.log(`Generated description field description: ${description}`);
      return description;
    }
    if (name.includes("comment")) {
      const description = `User-generated comment or remark associated with this ${entity} record`;
      console.log(`Generated comment description: ${description}`);
      return description;
    }
    if (name.includes("name") || name.includes("title")) {
      const fieldType = name.includes("name") ? "name" : "title";
      const description = `Primary ${fieldType} or identifier for this ${entity} record`;
      console.log(`Generated name/title description: ${description}`);
      return description;
    }
    if (name.includes("label")) {
      const description = `Display label or tag for this ${entity} record`;
      console.log(`Generated label description: ${description}`);
      return description;
    }
    if (name.includes("status")) {
      const description = `Current status or state of this ${entity} record`;
      console.log(`Generated status description: ${description}`);
      return description;
    }
    if (name.includes("state")) {
      const description = `Current state or condition of this ${entity} record`;
      console.log(`Generated state description: ${description}`);
      return description;
    }
    if (name.includes("type") || name.includes("category")) {
      const description = `Classification or category type for this ${entity} record`;
      console.log(`Generated type/category description: ${description}`);
      return description;
    }

    // Generic descriptions based on data type
    let description;
    switch (dataTypeInfo.type) {
      case "boolean":
        description = `Boolean flag for ${name.replace(
          /_/g,
          " "
        )} in the ${entity} dataset`;
        break;
      case "integer":
        description = `Integer value representing ${name.replace(
          /_/g,
          " "
        )} for this ${entity} record`;
        break;
      case "decimal":
        description = `Decimal/numeric value for ${name.replace(
          /_/g,
          " "
        )} in this ${entity} record`;
        break;
      case "datetime":
        description = `Date and time information for ${name.replace(
          /_/g,
          " "
        )} in this ${entity} record`;
        break;
      case "string":
      default:
        description = `Text information about ${name.replace(
          /_/g,
          " "
        )} for this ${entity} record`;
        break;
    }
    console.log(`Generated generic description: ${description}`);
    return description;
  };
  const [etlModal, setEtlModal] = useState({ open: false, column: "" });
  const [pysparkModal, setPysparkModal] = useState({ open: false, code: "" });
  const [sqlModal, setSqlModal] = useState({ open: false, code: "" });
  const [entityNLPModal, setEntityNLPModal] = useState({
    open: false,
    text: "",
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [descriptionModal, setDescriptionModal] = useState({
    open: false,
    column: "",
    description: "",
  });
  const [actionModal, setActionModal] = useState({
    open: false,
    type: "",
    column: "",
    data: null,
  });
  const [columnRules, setColumnRules] = useState({}); // Store NLP/DQ rules for each column
  const [concatenationRules, setConcatenationRules] = useState([]); // Store column concatenation rules
  const [operatorRules, setOperatorRules] = useState({}); // Store operator rules for each column
  const [entityNLPRules, setEntityNLPRules] = useState([]); // Store entity-level NLP rules
  const [columnDescriptions, setColumnDescriptions] = useState({}); // Store descriptions for each column
  const [autoGeneratedDescriptions, setAutoGeneratedDescriptions] = useState(
    new Set()
  ); // Track which descriptions are auto-generated
  const [consumptionFilesModal, setConsumptionFilesModal] = useState({
    open: false,
    files: [],
  });

  // Load saved transformations when component mounts
  useEffect(() => {
    if (!entityName) {
      console.log("No entity name available, skipping initialization");
      return;
    }

    const initializeData = async () => {
      console.log("Initializing data for entity:", entityName);
      // First load saved transformations (this will set mappings if they exist)
      const savedTransformationsFound = await loadSavedTransformations();
      // Then load schema only if no saved transformations were found
      await loadConsumptionSchema(savedTransformationsFound);
    };

    initializeData();
  }, [entityName, propConsumptionData, propRecords]);

  // Update mappings when records change (for prop-based data)
  useEffect(() => {
    console.log(
      "Records changed:",
      records.length,
      "Mappings length:",
      mappings.length
    );
    console.log(
      "Prop consumption data keys:",
      propConsumptionData ? Object.keys(propConsumptionData) : "No prop data"
    );
    console.log("Entity name:", entityName);

    if (records.length > 0 && mappings.length === 0) {
      const newAttributes = Object.keys(records[0]);
      console.log("Extracting attributes from records:", newAttributes);

      // Extract data types and descriptions from records
      const dataTypes = {};
      const descriptions = {};

      newAttributes.forEach((column) => {
        // Enhanced LLM-like data type detection
        const dataTypeInfo = generateLLMDataType(column, records);
        dataTypes[column] = dataTypeInfo;

        // Enhanced LLM-like description generation
        descriptions[column] = generateLLMDescription(
          column,
          dataTypeInfo,
          entityName
        );
      });

      setSchemaDataTypes(dataTypes);
      setSchemaDescriptions(descriptions);
      console.log("Set schema data types in useEffect:", dataTypes);
      console.log("Set schema descriptions in useEffect:", descriptions);

      const newMappings = newAttributes.map((attr) => ({
        gold: attr,
        value: attr,
        autogenerated: true,
      }));
      setMappings(newMappings);
      console.log("Updated mappings from records:", newMappings);
    } else if (records.length === 0 && mappings.length === 0 && entityName) {
      // Fallback: create some default mappings based on entity name
      console.log("No records available, creating fallback mappings");
      let fallbackAttributes = [];

      if (entityName.toLowerCase().includes("customer")) {
        fallbackAttributes = [
          "customer_id",
          "customer_name",
          "email",
          "phone",
          "address",
          "created_at",
        ];
      } else if (entityName.toLowerCase().includes("order")) {
        fallbackAttributes = [
          "order_id",
          "customer_id",
          "order_date",
          "total_amount",
          "status",
          "created_at",
        ];
      } else if (entityName.toLowerCase().includes("product")) {
        fallbackAttributes = [
          "product_id",
          "product_name",
          "category",
          "price",
          "description",
          "created_at",
        ];
      } else {
        fallbackAttributes = ["id", "name", "type", "created_at", "updated_at"];
      }

      // Generate fallback data types and descriptions (LLM simulation)
      const dataTypes = {};
      const descriptions = {};

      fallbackAttributes.forEach((attr) => {
        // Enhanced LLM-like data type detection
        const dataTypeInfo = generateLLMDataType(attr, []);
        dataTypes[attr] = dataTypeInfo;

        // Enhanced LLM-like description generation
        descriptions[attr] = generateLLMDescription(
          attr,
          dataTypeInfo,
          entityName
        );
      });

      setSchemaDataTypes(dataTypes);
      setSchemaDescriptions(descriptions);
      console.log("Set fallback schema data types:", dataTypes);
      console.log("Set fallback schema descriptions:", descriptions);

      const fallbackMappings = fallbackAttributes.map((attr) => ({
        gold: attr,
        value: attr,
        autogenerated: true,
      }));
      setMappings(fallbackMappings);
      console.log("Set fallback mappings:", fallbackMappings);
    }
  }, [records, mappings.length, propConsumptionData, entityName]);

  // Load consumption schema from database
  const loadConsumptionSchema = async (savedTransformationsFound = false) => {
    try {
      console.log("Loading consumption schema for entity:", entityName);

      // If saved transformations were found, don't override them
      if (savedTransformationsFound) {
        console.log("Saved transformations found, skipping schema loading");
        return;
      }

      // Check if we already have mappings (preserve existing transformations)
      if (mappings.length > 0) {
        console.log(
          "Mappings already exist, preserving transformations:",
          mappings
        );
        return; // Don't override existing transformations
      }

      // First, try to use prop data if available
      if (propConsumptionData && propConsumptionData[entityName]) {
        console.log("Using prop consumption data for entity:", entityName);
        const fileData = propConsumptionData[entityName];

        if (fileData && fileData.length > 0) {
          // Extract columns from the first record
          const columns = Object.keys(fileData[0]);
          console.log("Extracted columns from prop data:", columns);

          // Generate data types and descriptions for all columns (LLM simulation)
          const dataTypes = {};
          const descriptions = {};
          const autoGenerated = new Set();

          columns.forEach((column) => {
            // Enhanced LLM-like data type detection
            const dataTypeInfo = generateLLMDataType(column, fileData);
            dataTypes[column] = dataTypeInfo;

            // Enhanced LLM-like description generation
            descriptions[column] = generateLLMDescription(
              column,
              dataTypeInfo,
              entityName
            );
            // Mark as auto-generated if no user-saved description exists
            if (!columnDescriptions[column]) {
              autoGenerated.add(column);
            }
          });

          setSchemaDataTypes(dataTypes);
          setSchemaDescriptions(descriptions);
          setAutoGeneratedDescriptions(autoGenerated);
          console.log("Generated LLM-like data types:", dataTypes);
          console.log("Generated LLM-like descriptions:", descriptions);

          // Only set mappings if we don't have any existing ones
          if (mappings.length === 0) {
            const newMappings = columns.map((attr) => ({
              gold: attr,
              value: attr,
              autogenerated: true,
            }));

            setMappings(newMappings);
            console.log("Set initial mappings from prop data:", newMappings);
          }
          return;
        }
      }

      // Fallback: try to get schema from database
      const schemaResponse = await axios.get(
        `/api/consumption-schemas/${encodeURIComponent(entityName)}`
      );

      if (schemaResponse.data.success && schemaResponse.data.schema) {
        console.log(
          "Found consumption schema in database:",
          schemaResponse.data.schema
        );
        const schema = schemaResponse.data.schema;
        const columns = schema.schemaAttributes || [];

        console.log("Using consumption schema from database:", columns);

        // Generate data types and descriptions for all columns (LLM simulation)
        const dataTypes = {};
        const descriptions = {};

        columns.forEach((column) => {
          // Enhanced LLM-like data type detection
          const dataTypeInfo = generateLLMDataType(column, []);
          dataTypes[column] = dataTypeInfo;

          // Enhanced LLM-like description generation
          descriptions[column] = generateLLMDescription(
            column,
            dataTypeInfo,
            entityName
          );
        });

        setSchemaDataTypes(dataTypes);
        setSchemaDescriptions(descriptions);
        console.log("Generated LLM-like data types:", dataTypes);
        console.log("Generated LLM-like descriptions:", descriptions);

        // Only set mappings if we don't have any existing ones
        if (mappings.length === 0) {
          const newMappings = columns.map((attr) => ({
            gold: attr,
            value: attr,
            autogenerated: true,
          }));

          setMappings(newMappings);
          console.log("Set initial mappings from stored schema:", newMappings);
        }
      } else {
        console.log("No consumption schema found in database, using fallback");
        // Only set mappings if we don't have any existing ones
        if (mappings.length === 0) {
          const fallbackAttributes = outputColumns.length
            ? outputColumns.map((col) => col.name)
            : records[0]
            ? Object.keys(records[0])
            : ["id", "name", "type", "created_at"];

          // Generate fallback data types and descriptions (LLM simulation)
          const dataTypes = {};
          const descriptions = {};

          fallbackAttributes.forEach((attr) => {
            // Enhanced LLM-like data type detection
            const dataTypeInfo = generateLLMDataType(attr, []);
            dataTypes[attr] = dataTypeInfo;

            // Enhanced LLM-like description generation
            descriptions[attr] = generateLLMDescription(
              attr,
              dataTypeInfo,
              entityName
            );
          });

          setSchemaDataTypes(dataTypes);
          setSchemaDescriptions(descriptions);

          const fallbackMappings = fallbackAttributes.map((attr) => ({
            gold: attr,
            value: attr,
            autogenerated: true,
          }));

          setMappings(fallbackMappings);
          console.log("Set fallback mappings:", fallbackMappings);
        }
      }
    } catch (error) {
      console.log("Error loading consumption schema:", error.message);
      // Only set mappings if we don't have any existing ones
      if (mappings.length === 0) {
        const fallbackAttributes = outputColumns.length
          ? outputColumns.map((col) => col.name)
          : records[0]
          ? Object.keys(records[0])
          : ["id", "name", "type", "created_at"];

        // Generate fallback data types and descriptions (LLM simulation)
        const dataTypes = {};
        const descriptions = {};

        fallbackAttributes.forEach((attr) => {
          // Enhanced LLM-like data type detection
          const dataTypeInfo = generateLLMDataType(attr, []);
          dataTypes[attr] = dataTypeInfo;

          // Enhanced LLM-like description generation
          descriptions[attr] = generateLLMDescription(
            attr,
            dataTypeInfo,
            entityName
          );
        });

        setSchemaDataTypes(dataTypes);
        setSchemaDescriptions(descriptions);

        const fallbackMappings = fallbackAttributes.map((attr) => ({
          gold: attr,
          value: attr,
          autogenerated: true,
        }));

        setMappings(fallbackMappings);
        console.log("Set error fallback mappings:", fallbackMappings);
      }
    }
  };

  // Load saved transformations from backend
  const loadSavedTransformations = async () => {
    try {
      const response = await axios.get(
        `/api/transformations/${entityName}?fileType=consumption`
      );

      if (response.data.success && response.data.transformations) {
        const saved = response.data.transformations;

        // Restore saved state
        if (saved.mappings) {
          setMappings(saved.mappings);
          console.log("Loaded saved mappings:", saved.mappings);
        }
        if (saved.columnRules) {
          setColumnRules(saved.columnRules);
        }
        if (saved.operatorRules) {
          setOperatorRules(saved.operatorRules);
        }
        if (saved.concatenationRules) {
          setConcatenationRules(saved.concatenationRules);
        }
        if (saved.entityNLPRules) {
          setEntityNLPRules(saved.entityNLPRules);
        }
        if (saved.columnDescriptions) {
          setColumnDescriptions(saved.columnDescriptions);

          // Remove user-saved descriptions from auto-generated set
          const updatedAutoGenerated = new Set(autoGeneratedDescriptions);
          Object.keys(saved.columnDescriptions).forEach((column) => {
            updatedAutoGenerated.delete(column);
          });
          setAutoGeneratedDescriptions(updatedAutoGenerated);
        }

        console.log("Loaded saved transformations for entity:", entityName);
        return true; // Indicate that saved transformations were found
      }
    } catch (error) {
      console.log("No saved transformations found for entity:", entityName);
      // This is normal for new entities, so we don't show an error
    }
    return false; // Indicate that no saved transformations were found
  };

  // Load consumption files
  const loadConsumptionFiles = async () => {
    try {
      const response = await axios.get("/api/ai-consumption-files");
      if (response.data && response.data.files) {
        setConsumptionFilesModal({ open: true, files: response.data.files });
        setShowConsumptionModal(true);
      }
    } catch (error) {
      console.error("Failed to load consumption files:", error);
      alert("Failed to load consumption files. Please try again.");
    }
  };

  // Update mapping
  const updateMapping = (idx, field, value) => {
    setMappings((m) =>
      m.map((row, i) =>
        i === idx ? { ...row, [field]: value, autogenerated: false } : row
      )
    );
  };

  // Delete mapping
  const deleteMapping = (idx) => {
    setMappings((m) => m.filter((_, i) => i !== idx));
  };

  // Add new mapping row
  const addMapping = () => {
    setMappings((m) => [
      ...m,
      {
        gold: "", // Empty for new columns - will show "New Column" text
        value: "", // User will enter custom name
        autogenerated: false,
        isNewColumn: true, // Flag to identify new columns
      },
    ]);
  };

  const handleEntityTransformation = () => {
    setEtlModal({ open: true, column: entityName });
  };

  // Handler stubs
  const generatePySparkCode = () => {
    let code = `# PySpark Code for Entity: ${entityName}\n`;
    code += `from pyspark.sql import SparkSession\n`;
    code += `from pyspark.sql.functions import *\n\n`;

    code += `# Initialize Spark session\n`;
    code += `spark = SparkSession.builder.appName("${entityName}_processing").getOrCreate()\n\n`;

    code += `# Read the gold data\n`;
    code += `df = spark.read.format("parquet").load("path/to/gold/data")\n\n`;

    code += `# Apply transformations\n`;

    // Add NLP transformations
    Object.keys(columnRules).forEach((column) => {
      const rules = columnRules[column];
      if (rules.nlp && rules.nlp.length > 0) {
        code += `# NLP transformations for column: ${column}\n`;
        rules.nlp.forEach((rule) => {
          if (rule.enabled) {
            switch (rule.type) {
              case "uppercase":
                code += `df = df.withColumn("${column}", upper(col("${column}")))\n`;
                break;
              case "lowercase":
                code += `df = df.withColumn("${column}", lower(col("${column}")))\n`;
                break;
              case "title_case":
                code += `df = df.withColumn("${column}", initcap(col("${column}")))\n`;
                break;
              case "remove_special_chars":
                code += `df = df.withColumn("${column}", regexp_replace(col("${column}"), "[^a-zA-Z0-9\\s]", ""))\n`;
                break;
              case "trim_whitespace":
                code += `df = df.withColumn("${column}", trim(col("${column}")))\n`;
                break;
            }
          }
        });
        code += `\n`;
      }
    });

    // Add DQ validations
    Object.keys(columnRules).forEach((column) => {
      const rules = columnRules[column];
      if (rules.dq && rules.dq.length > 0) {
        code += `# Data Quality validations for column: ${column}\n`;
        rules.dq.forEach((rule) => {
          if (rule.enabled) {
            switch (rule.type) {
              case "not_null":
                code += `df = df.filter(col("${column}").isNotNull())\n`;
                break;
              case "unique":
                code += `df = df.dropDuplicates(["${column}"])\n`;
                break;
              case "email_format":
                code += `df = df.filter(col("${column}").rlike("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"))\n`;
                break;
              case "numeric_only":
                code += `df = df.filter(col("${column}").cast("double").isNotNull())\n`;
                break;
            }
          }
        });
        code += `\n`;
      }
    });

    // Add operator rules
    Object.keys(operatorRules).forEach((column) => {
      const rules = operatorRules[column];
      if (rules && rules.length > 0) {
        code += `# Operator rules for column: ${column}\n`;
        rules.forEach((rule) => {
          if (rule.enabled) {
            switch (rule.type) {
              case "greater_than":
                code += `df = df.filter(col("${column}") > ${rule.value})\n`;
                break;
              case "less_than":
                code += `df = df.filter(col("${column}") < ${rule.value})\n`;
                break;
              case "equals":
                code += `df = df.filter(col("${column}") == "${rule.value}")\n`;
                break;
              case "not_equals":
                code += `df = df.filter(col("${column}") != "${rule.value}")\n`;
                break;
              case "greater_than_equal":
                code += `df = df.filter(col("${column}") >= ${rule.value})\n`;
                break;
              case "less_than_equal":
                code += `df = df.filter(col("${column}") <= ${rule.value})\n`;
                break;
              case "between":
                const [min, max] = rule?.value
                  ?.split?.(",")
                  ?.map((v) => v?.trim());
                code += `df = df.filter((col("${column}") >= ${min}) & (col("${column}") <= ${max}))\n`;
                break;
              case "in_list":
                const values = rule?.value
                  ?.split?.(",")
                  ?.map((v) => `"${v?.trim()}"`)
                  ?.join?.(", ");
                code += `df = df.filter(col("${column}").isin(${values}))\n`;
                break;
            }
          }
        });
        code += `\n`;
      }
    });

    // Add concatenation rules
    if (concatenationRules.length > 0) {
      code += `# Column concatenations\n`;
      concatenationRules.forEach((rule) => {
        const concatExpr = rule.sourceColumns
          .map((col) => `col("${col}")`)
          .join?.(` + lit("${rule.separator}") + `);
        code += `df = df.withColumn("${rule.targetColumn}", ${concatExpr})\n`;
      });
      code += `\n`;
    }

    code += `# Write the processed data\n`;
    code += `df.write.mode("overwrite").parquet("path/to/consumption/data")\n`;
    code += `\nspark.stop()\n`;

    setPysparkModal({ open: true, code });
    setShowPySparkModal(true);
  };

  const generateSQLCode = () => {
    let code = `-- SQL Code for Entity: ${entityName}\n`;
    code += `-- Create consumption table with transformations\n\n`;

    code += `CREATE TABLE IF NOT EXISTS consumption_${entityName} (\n`;

    // Add all attributes as columns
    attributes.forEach((attr, idx) => {
      let dataType = "VARCHAR(255)"; // Default type

      // Determine data type based on column name or rules
      if (attr.includes("timestamp") || attr.includes("date")) {
        dataType = "TIMESTAMP";
      } else if (attr.includes("id") || attr.includes("_id")) {
        dataType = "BIGINT";
      } else if (
        attr.includes("amount") ||
        attr.includes("price") ||
        attr.includes("cost")
      ) {
        dataType = "DECIMAL(10,2)";
      } else if (attr.includes("quantity") || attr.includes("count")) {
        dataType = "INTEGER";
      } else if (attr === "is_deleted" || attr.includes("is_")) {
        dataType = "BOOLEAN";
      }

      code += `    ${attr} ${dataType}`;
      if (idx < attributes.length - 1) code += ",";
      code += `\n`;
    });

    code += `);\n\n`;

    code += `-- Insert transformed data\n`;
    code += `INSERT INTO consumption_${entityName}\n`;
    code += `SELECT\n`;

    // Add column mappings with transformations
    mappings.forEach((mapping, idx) => {
      let columnExpr = mapping.gold;

      // Apply NLP transformations if any
      const nlpRules = columnRules[mapping.value]?.nlp || [];
      nlpRules.forEach((rule) => {
        if (rule.enabled) {
          switch (rule.type) {
            case "uppercase":
              columnExpr = `UPPER(${columnExpr})`;
              break;
            case "lowercase":
              columnExpr = `LOWER(${columnExpr})`;
              break;
            case "trim_whitespace":
              columnExpr = `TRIM(${columnExpr})`;
              break;
            case "remove_special_chars":
              columnExpr = `REGEXP_REPLACE(${columnExpr}, '[^a-zA-Z0-9\\s]', '')`;
              break;
          }
        }
      });

      code += `    ${columnExpr} as ${mapping.value}`;
      if (idx < mappings.length - 1) code += ",";
      code += `\n`;
    });

    code += `FROM gold_${entityName};\n\n`;

    // Add data quality checks
    code += `-- Data Quality Checks\n`;
    Object.keys(columnRules).forEach((column) => {
      const rules = columnRules[column];
      if (rules.dq && rules.dq.length > 0) {
        code += `-- DQ checks for ${column}\n`;
        rules.dq.forEach((rule) => {
          if (rule.enabled) {
            switch (rule.type) {
              case "not_null":
                code += `-- ${column} should not be null\n`;
                break;
              case "unique":
                code += `-- ${column} should be unique\n`;
                break;
              case "email_format":
                code += `-- ${column} should be valid email format\n`;
                break;
            }
          }
        });
      }
    });

    setSqlModal({ open: true, code });
    setShowSqlModal(true);
  };

  const handleEntityNLP = () => {
    setEntityNLPModal({ open: true, text: "" });
    setShowNlpModal(true);
  };

  const saveEntityNLP = () => {
    if (entityNLPModal.text.trim()) {
      const newRule = {
        id: Date.now(),
        text: entityNLPModal.text.trim(),
        enabled: true,
        createdAt: new Date().toISOString(),
      };

      setEntityNLPRules((prev) => [...prev, newRule]);
      setEntityNLPModal({ open: false, text: "" });
    } else {
      alert("Please enter NLP processing requirements before saving.");
    }
  };

  const deleteEntityNLPRule = (ruleId) => {
    setEntityNLPRules((prev) => prev.filter((rule) => rule.id !== ruleId));
  };

  const handleConcatenateColumns = () => {
    setActionModal({
      open: true,
      type: "concatenate",
      column: "",
      data: {
        sourceColumns: [],
        targetColumn: "",
        separator: " ",
        existingRules: concatenationRules,
      },
    });
  };

  const saveMappingsOnly = async () => {
    // Validate new columns have target names
    const incompleteNewColumns = mappings.filter(
      (mapping) => mapping.isNewColumn && !mapping.value.trim()
    );

    if (incompleteNewColumns.length > 0) {
      alert(
        "Please complete all new column mappings. New columns must have a target column name filled in."
      );
      return;
    }

    setIsSaving(true);
    try {
      const transformations = {
        entityName: entityName,
        mappings: mappings,
        columnRules: columnRules,
        operatorRules: operatorRules,
        concatenationRules: concatenationRules,
        entityNLPRules: entityNLPRules,
        columnDescriptions: columnDescriptions,
      };

      const response = await axios.post("/api/transformations/save-mappings", {
        entityName: entityName,
        transformations: transformations,
        fileType: "consumption",
      });

      console.log("Mappings saved:", response.data);
      alert("Mappings saved successfully!");
    } catch (error) {
      console.error("Failed to save mappings:", error);
      alert("Failed to save mappings. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  const saveTransformationsAndGenerateConsumptionFile = async () => {
    // Validate new columns have target names
    const incompleteNewColumns = mappings.filter(
      (mapping) => mapping.isNewColumn && !mapping.value.trim()
    );

    if (incompleteNewColumns.length > 0) {
      alert(
        "Please complete all new column mappings. New columns must have a target column name filled in."
      );
      return;
    }

    setIsGenerating(true);
    try {
      const transformations = {
        entityName: entityName,
        mappings: mappings,
        columnRules: columnRules,
        operatorRules: operatorRules,
        concatenationRules: concatenationRules,
        entityNLPRules: entityNLPRules,
        columnDescriptions: columnDescriptions,
      };

      // First save the transformations
      await axios.post("/api/transformations/save-mappings", {
        entityName: entityName,
        transformations: transformations,
        fileType: "consumption",
      });

      // Get the actual data from AI consumption files for this entity
      let localData = records; // Use existing records if available

      if (!localData || localData.length === 0) {
        try {
          console.log("Fetching local data for entity:", entityName);
          const aiResponse = await axios.get("/api/ai-consumption-files");
          if (
            aiResponse.data &&
            aiResponse.data.consumptionData &&
            aiResponse.data.consumptionData[entityName]
          ) {
            localData = aiResponse.data.consumptionData[entityName];
            console.log(
              "Found local data for entity:",
              entityName,
              "Records:",
              localData.length
            );
          } else {
            console.log("No local data found for entity:", entityName);
          }
        } catch (aiError) {
          console.error("Error fetching AI consumption data:", aiError);
        }
      }

      // Then generate the consumption file
      const response = await axios.post("/api/consumption/generate", {
        entityName: entityName,
        consumptionEntityName: `consumption.${entityName}`,
        sourceFileKey: `gold/${entityName}.csv`, // Assuming gold files are stored in gold/ folder
        transformations: transformations,
        localData: localData, // Pass local data as fallback when S3 file doesn't exist
      });

      console.log(
        "Transformations saved and consumption file generated:",
        response.data
      );
      alert(
        "Transformations saved and consumption file generated successfully!"
      );
    } catch (error) {
      console.error("Failed to save transformations:", error);
      alert("Failed to process entity. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const [showRenameModal, setShowRenameModal] = useState(false);
  const [showDescModal, setShowDescModal] = useState(false);
  const [showPySparkModal, setShowPySparkModal] = useState(false);
  const [showSqlModal, setShowSqlModal] = useState(false);
  const [showNlpModal, setShowNlpModal] = useState(false);
  const [showConsumptionModal, setShowConsumptionModal] = useState(false);

  // Attribute-level action handlers
  const handleColumnRename = (columnName) => {
    setActionModal({
      open: true,
      type: "rename",
      column: columnName,
      data: { newName: "" },
    });
    setShowRenameModal(true);
  };

  const handleColumnMapping = (columnName) => {
    setActionModal({
      open: true,
      type: "mapping",
      column: columnName,
      data: { targetColumn: "", mappingType: "direct" },
    });
  };

  const handleNLPRules = (columnName) => {
    setActionModal({
      open: true,
      type: "nlp",
      column: columnName,
      data: {
        rules: columnRules[columnName]?.nlp || [],
        newRule: { type: "uppercase", enabled: true, parameters: {} },
      },
    });
  };

  const handleDQRules = (columnName) => {
    setActionModal({
      open: true,
      type: "dq",
      column: columnName,
      data: {
        rules: columnRules[columnName]?.dq || [],
        newRule: { type: "not_null", enabled: true, parameters: {} },
      },
    });
  };

  const handleOperatorRules = (columnName) => {
    setActionModal({
      open: true,
      type: "operator",
      column: columnName,
      data: {
        rules: operatorRules[columnName] || [],
        newRule: {
          type: "greater_than",
          enabled: true,
          value: 0,
          operator: ">",
        },
      },
    });
  };

  const handleSaveAction = () => {
    const { type, column, data } = actionModal;

    switch (type) {
      case "rename":
        // Update the column name in attributes
        const newAttributes = attributes.map((attr) =>
          attr === column ? data.newName : attr
        );
        // Update mappings to use the new column name
        setMappings((prev) =>
          prev.map((mapping) =>
            mapping.value === column
              ? { ...mapping, value: data.newName }
              : mapping
          )
        );
        break;

      case "mapping":
        // Update the mapping for the column
        setMappings((prev) =>
          prev.map((mapping) =>
            mapping.value === column
              ? {
                  ...mapping,
                  value: data.targetColumn,
                  mappingType: data.mappingType,
                }
              : mapping
          )
        );
        break;

      case "nlp":
        // Save NLP rules for the column
        setColumnRules((prev) => ({
          ...prev,
          [column]: { ...prev[column], nlp: [...data.rules, data.newRule] },
        }));
        break;

      case "dq":
        // Save DQ rules for the column
        setColumnRules((prev) => ({
          ...prev,
          [column]: { ...prev[column], dq: [...data.rules, data.newRule] },
        }));
        break;

      case "operator":
        // Save operator rules for the column
        setOperatorRules((prev) => ({
          ...prev,
          [column]: [...data.rules, data.newRule],
        }));
        break;

      case "concatenate":
        // Add concatenation rule
        setConcatenationRules((prev) => [
          ...prev,
          {
            id: Date.now(),
            sourceColumns: data.sourceColumns,
            targetColumn: data.targetColumn,
            separator: data.separator,
          },
        ]);
        break;
    }

    setActionModal({ open: false, type: "", column: "", data: null });
  };

  const handleDeleteConcatenationRule = (ruleId) => {
    setConcatenationRules((prev) => prev.filter((rule) => rule.id !== ruleId));
  };

  const handleColumnDescription = (columnName) => {
    // Get description from user-saved descriptions first, then fall back to auto-generated
    const userDescription = columnDescriptions[columnName];
    const autoGeneratedDescription = schemaDescriptions[columnName];
    const description = userDescription || autoGeneratedDescription || "";

    setDescriptionModal({
      open: true,
      column: columnName,
      description: description,
    });
    setShowDescModal(true);
  };

  const saveColumnDescription = async () => {
    if (descriptionModal.column && descriptionModal.description.trim()) {
      // Update the column descriptions state
      const updatedColumnDescriptions = {
        ...columnDescriptions,
        [descriptionModal.column]: descriptionModal.description.trim(),
      };
      setColumnDescriptions(updatedColumnDescriptions);

      // Remove from auto-generated set when user saves a description
      const updatedAutoGenerated = new Set(autoGeneratedDescriptions);
      updatedAutoGenerated.delete(descriptionModal.column);
      setAutoGeneratedDescriptions(updatedAutoGenerated);
      setDescriptionModal({ open: false, column: "", description: "" });

      // Auto-save mappings when description is saved
      try {
        const transformations = {
          entityName: entityName,
          mappings: mappings,
          columnRules: columnRules,
          operatorRules: operatorRules,
          concatenationRules: concatenationRules,
          entityNLPRules: entityNLPRules,
          columnDescriptions: updatedColumnDescriptions,
        };

        const response = await axios.post(
          "/api/transformations/save-mappings",
          {
            entityName: entityName,
            transformations: transformations,
            fileType: "consumption",
          }
        );

        console.log("Mappings auto-saved with description:", response.data);
      } catch (error) {
        console.error("Failed to auto-save mappings:", error);
        alert(
          "Description saved but failed to auto-save mappings. Please save manually."
        );
      }
    } else {
      alert("Please enter a description for the column.");
    }
  };

  const deleteColumnDescription = (columnName) => {
    setColumnDescriptions((prev) => {
      const updated = { ...prev };
      delete updated[columnName];
      return updated;
    });
  };

  // Derive attributes from mappings for rendering
  const currentAttributes = mappings.map((m) => m.gold).filter((attr) => attr);

  // Defensive rendering for missing data
  if (!mappings.length) {
    return (
      <div className="edit-consumption-entity-mappings-page">
        <h2 className="ecem-title">Edit Consumption Entity Mappings</h2>
        <div style={{ color: "#ff6b35", padding: "2rem", textAlign: "center" }}>
          Loading entity data... Please wait.
        </div>
      </div>
    );
  }

  // Force generate data types and descriptions for all mappings if they don't exist
  useEffect(() => {
    if (mappings.length > 0 && Object.keys(schemaDataTypes).length === 0) {
      console.log(
        "Forcing generation of data types and descriptions for all mappings"
      );
      const dataTypes = {};
      const descriptions = {};
      const autoGenerated = new Set();

      mappings.forEach((mapping) => {
        if (mapping.value) {
          const dataTypeInfo = generateLLMDataType(mapping.value, records);
          dataTypes[mapping.value] = dataTypeInfo;
          descriptions[mapping.value] = generateLLMDescription(
            mapping.value,
            dataTypeInfo,
            entityName
          );
          // Mark as auto-generated if no user-saved description exists
          if (!columnDescriptions[mapping.value]) {
            autoGenerated.add(mapping.value);
          }
        }
      });

      setSchemaDataTypes(dataTypes);
      setSchemaDescriptions(descriptions);
      setAutoGeneratedDescriptions(autoGenerated);
      console.log("Forced generation - data types:", dataTypes);
      console.log("Forced generation - descriptions:", descriptions);
      console.log("Auto-generated columns:", Array.from(autoGenerated));
    }
  }, [mappings, schemaDataTypes, records, entityName]);

  console.log("Current schemaDataTypes state:", schemaDataTypes);
  console.log("Current schemaDescriptions state:", schemaDescriptions);
  console.log("Current mappings:", mappings);

  return (
    <>
      {/* Collaborative editing presence */}
      <div style={{ marginBottom: '16px', display: 'flex', gap: '12px', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ flex: 1 }}>
          <CollaborationBanner
            activeUsers={activeUsers}
            currentUserId={currentUserId}
            onRefresh={() => window.location.reload()}
          />
        </div>
        <PresenceIndicator
          activeUsers={activeUsers}
          currentUserId={currentUserId}
          maxVisible={5}
          showCount={true}
        />
      </div>

      <div className="bg-light rounded p-3">
        <ColumnETLModal
          open={etlModal.open}
          onClose={() => setEtlModal({ open: false, column: "" })}
          column={etlModal.column}
          entityColumns={attributes}
        />

        {mappings.some((m) => m.isNewColumn) && (
          <div style={{ backgroundColor: "#e8f5e8", fontSize: "0.8rem" }}>
            <Alert variant="success">
              <div className="alert-icon">
                <BiBulb fontSize={24} />
              </div>
              <div className="alert-text text-start">
                New columns (highlighted in green) allow you to create custom
                columns with custom names. Complete columns show green border,
                incomplete ones show yellow border and warning icon. Data types
                and descriptions are auto-generated using LLM simulation for
                every attribute.
              </div>
            </Alert>
          </div>
        )}
        {mappings.map((row, idx) => (
          <Row className="mb-2" key={idx}>
            <Col md={{ span: 3, offset: 5 }}>
              <div className="d-flex gap-2 align-items-center bg-white border rounded p-2">
                {row.isNewColumn ? (
                  <Form.Control
                    type="text"
                    size="sm"
                    value={row.value}
                    onChange={(e) =>
                      updateMapping(idx, "value", e.target.value)
                    }
                    placeholder="Enter new column name"
                  />
                ) : (
                  <>
                    <Form.Select
                      style={{ backgroundImage: "none" }}
                      className="bg-transparent border-0 fw-medium py-0 px-2 h-auto w-auto"
                      value={row.value}
                      onChange={(e) =>
                        updateMapping(idx, "value", e.target.value)
                      }
                      disabled={true}
                    >
                      {currentAttributes.map((attr) => (
                        <option key={attr} value={attr}>
                          {attr}
                        </option>
                      ))}
                    </Form.Select>
                  </>
                )}
                {schemaDataTypes[row.value] ? (
                  <Badge
                    bg="dark"
                    className="text-sm bg-light text-dark"
                    title={`Type: ${
                      schemaDataTypes[row.value].type
                    }, Nullable: ${schemaDataTypes[row.value].nullable}`}
                  >
                    {schemaDataTypes[row.value].type}
                    {schemaDataTypes[row.value].nullable && <>(nullable)</>}
                  </Badge>
                ) : (
                  <>Unknown</>
                )}
              </div>
            </Col>

            <Col md={{ span: 2, offset: 2 }} className="text-center">
              <OverlayTrigger
                placement="top"
                overlay={
                  <Tooltip>
                    {!columnDescriptions[row.value] &&
                    schemaDescriptions[row.value]
                      ? "Auto-generated description (click to edit)"
                      : "Add/edit column description"}
                  </Tooltip>
                }
              >
                <Button
                  variant="outline-secondary bg-white btn-icon"
                  size="sm"
                  onClick={() => handleColumnDescription(row.value)}
                  style={{ position: "relative" }}
                >
                  <BiSpreadsheet />
                  {!columnDescriptions[row.value] &&
                    schemaDescriptions[row.value] && (
                      <span
                        style={{
                          position: "absolute",
                          top: "-2px",
                          right: "-2px",
                          background: "#28a745",
                          color: "white",
                          borderRadius: "50%",
                          width: "12px",
                          height: "12px",
                          fontSize: "8px",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                        }}
                        title="Auto-generated"
                      >
                        A
                      </span>
                    )}
                </Button>
              </OverlayTrigger>
            </Col>
          </Row>
        ))}

        <Row>
          <Col md={{ span: 7, offset: 5 }}>
            <Button
              variant="link ps-0"
              onClick={() =>
                onSwitchToCanvas && onSwitchToCanvas(entityName, records)
              }
              title="Switch to canvas view to add columns"
            >
              + Add New Attribute
            </Button>
          </Col>
        </Row>

        {/* Action Modal */}
        {actionModal.open && (
          <Modal
            show={showRenameModal}
            onHide={() => setShowRenameModal(false)}
            centered
            backdrop="static"
          >
            <Modal.Header closeButton>
              <Modal.Title>
                {actionModal.type === "rename" && "Rename Column"}
                {actionModal.type === "mapping" && "Map Column"}
                {actionModal.type === "nlp" && "NLP Rules"}
                {actionModal.type === "dq" && "Data Quality Rules"}
                {actionModal.type === "operator" && "Operator Rules"}
                {actionModal.type === "concatenate" && "Concatenate Columns"}
              </Modal.Title>
            </Modal.Header>
            <Modal.Body>
              {/* Rename Column */}
              {actionModal.type === "rename" && (
                <Form.Group>
                  <Form.Label>
                    <span className="text-muted">Rename column:</span>{" "}
                    <strong>{actionModal.column}</strong>
                  </Form.Label>
                  <Form.Control
                    type="text"
                    placeholder="New column name"
                    value={actionModal.data.newName}
                    onChange={(e) =>
                      setActionModal((prev) => ({
                        ...prev,
                        data: { ...prev.data, newName: e.target.value },
                      }))
                    }
                  />
                </Form.Group>
              )}

              {/* Map Column */}
              {actionModal.type === "mapping" && (
                <div>
                  <p>
                    Map column: <strong>{actionModal.column}</strong>
                  </p>
                  <select
                    value={actionModal.data.targetColumn}
                    onChange={(e) =>
                      setActionModal((prev) => ({
                        ...prev,
                        data: {
                          ...prev.data,
                          targetColumn: e.target.value,
                        },
                      }))
                    }
                    style={{
                      width: "100%",
                      padding: "8px",
                      border: "1px solid #ddd",
                      borderRadius: "4px",
                      marginBottom: "1rem",
                    }}
                  >
                    <option value="">Select target column</option>
                    {currentAttributes
                      .filter((attr) => attr !== actionModal.column)
                      .map((attr) => (
                        <option key={attr} value={attr}>
                          {attr}
                        </option>
                      ))}
                  </select>
                  <select
                    value={actionModal.data.mappingType}
                    onChange={(e) =>
                      setActionModal((prev) => ({
                        ...prev,
                        data: { ...prev.data, mappingType: e.target.value },
                      }))
                    }
                    style={{
                      width: "100%",
                      padding: "8px",
                      border: "1px solid #ddd",
                      borderRadius: "4px",
                      marginBottom: "1rem",
                    }}
                  >
                    <option value="direct">Direct Mapping</option>
                    <option value="transform">Transform</option>
                    <option value="conditional">Conditional</option>
                  </select>
                </div>
              )}

              {/* NLP Rules */}
              {actionModal.type === "nlp" && (
                <div>
                  <p>
                    NLP Rules for: <strong>{actionModal.column}</strong>
                  </p>
                  <div style={{ marginBottom: "1rem" }}>
                    <select
                      value={actionModal.data.newRule.type}
                      onChange={(e) =>
                        setActionModal((prev) => ({
                          ...prev,
                          data: {
                            ...prev.data,
                            newRule: {
                              ...prev.data.newRule,
                              type: e.target.value,
                            },
                          },
                        }))
                      }
                      style={{
                        width: "100%",
                        padding: "8px",
                        border: "1px solid #ddd",
                        borderRadius: "4px",
                        marginBottom: "0.5rem",
                      }}
                    >
                      <option value="uppercase">Convert to Uppercase</option>
                      <option value="lowercase">Convert to Lowercase</option>
                      <option value="title_case">Convert to Title Case</option>
                      <option value="remove_special_chars">
                        Remove Special Characters
                      </option>
                      <option value="trim_whitespace">Trim Whitespace</option>
                    </select>
                    <label
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "0.5rem",
                      }}
                    >
                      <input
                        type="checkbox"
                        checked={actionModal.data.newRule.enabled}
                        onChange={(e) =>
                          setActionModal((prev) => ({
                            ...prev,
                            data: {
                              ...prev.data,
                              newRule: {
                                ...prev.data.newRule,
                                enabled: e.target.checked,
                              },
                            },
                          }))
                        }
                      />
                      Enable Rule
                    </label>
                  </div>
                  <div style={{ marginBottom: "1rem" }}>
                    <h4>Current Rules:</h4>
                    {actionModal.data.rules.map((rule, idx) => (
                      <div
                        key={idx}
                        style={{
                          padding: "0.5rem",
                          background: "#f5f5f5",
                          marginBottom: "0.5rem",
                          borderRadius: "4px",
                        }}
                      >
                        {rule.type} - {rule.enabled ? "Enabled" : "Disabled"}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* DQ Rules */}
              {actionModal.type === "dq" && (
                <div>
                  <p>
                    Data Quality Rules for:{" "}
                    <strong>{actionModal.column}</strong>
                  </p>
                  <div style={{ marginBottom: "1rem" }}>
                    <select
                      value={actionModal.data.newRule.type}
                      onChange={(e) =>
                        setActionModal((prev) => ({
                          ...prev,
                          data: {
                            ...prev.data,
                            newRule: {
                              ...prev.data.newRule,
                              type: e.target.value,
                            },
                          },
                        }))
                      }
                      style={{
                        width: "100%",
                        padding: "8px",
                        border: "1px solid #ddd",
                        borderRadius: "4px",
                        marginBottom: "0.5rem",
                      }}
                    >
                      <option value="not_null">Not Null</option>
                      <option value="unique">Unique Values</option>
                      <option value="email_format">Email Format</option>
                      <option value="numeric_only">Numeric Only</option>
                    </select>
                    <label
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "0.5rem",
                      }}
                    >
                      <input
                        type="checkbox"
                        checked={actionModal.data.newRule.enabled}
                        onChange={(e) =>
                          setActionModal((prev) => ({
                            ...prev,
                            data: {
                              ...prev.data,
                              newRule: {
                                ...prev.data.newRule,
                                enabled: e.target.checked,
                              },
                            },
                          }))
                        }
                      />
                      Enable Rule
                    </label>
                  </div>
                  <div style={{ marginBottom: "1rem" }}>
                    <h4>Current Rules:</h4>
                    {actionModal.data.rules.map((rule, idx) => (
                      <div
                        key={idx}
                        style={{
                          padding: "0.5rem",
                          background: "#f5f5f5",
                          marginBottom: "0.5rem",
                          borderRadius: "4px",
                        }}
                      >
                        {rule.type} - {rule.enabled ? "Enabled" : "Disabled"}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Operator Rules */}
              {actionModal.type === "operator" && (
                <div>
                  <p>
                    Operator Rules for: <strong>{actionModal.column}</strong>
                  </p>
                  <div style={{ marginBottom: "1rem" }}>
                    <select
                      value={actionModal.data.newRule.type}
                      onChange={(e) =>
                        setActionModal((prev) => ({
                          ...prev,
                          data: {
                            ...prev.data,
                            newRule: {
                              ...prev.data.newRule,
                              type: e.target.value,
                            },
                          },
                        }))
                      }
                      style={{
                        width: "100%",
                        padding: "8px",
                        border: "1px solid #ddd",
                        borderRadius: "4px",
                        marginBottom: "0.5rem",
                      }}
                    >
                      <option value="greater_than">Greater Than</option>
                      <option value="less_than">Less Than</option>
                      <option value="equals">Equals</option>
                      <option value="not_equals">Not Equals</option>
                      <option value="between">Between</option>
                      <option value="in_list">In List</option>
                    </select>

                    <input
                      type="text"
                      placeholder="Value (e.g., 60, 'text', 100,200 for between)"
                      value={actionModal.data.newRule.value || ""}
                      onChange={(e) =>
                        setActionModal((prev) => ({
                          ...prev,
                          data: {
                            ...prev.data,
                            newRule: {
                              ...prev.data.newRule,
                              value: e.target.value,
                            },
                          },
                        }))
                      }
                      style={{
                        width: "100%",
                        padding: "8px",
                        border: "1px solid #ddd",
                        borderRadius: "4px",
                        marginBottom: "0.5rem",
                      }}
                    />

                    <label
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "0.5rem",
                      }}
                    >
                      <input
                        type="checkbox"
                        checked={actionModal.data.newRule.enabled}
                        onChange={(e) =>
                          setActionModal((prev) => ({
                            ...prev,
                            data: {
                              ...prev.data,
                              newRule: {
                                ...prev.data.newRule,
                                enabled: e.target.checked,
                              },
                            },
                          }))
                        }
                      />
                      Enable Rule
                    </label>
                  </div>
                  <div style={{ marginBottom: "1rem" }}>
                    <h4>Current Rules:</h4>
                    {actionModal.data.rules.map((rule, idx) => (
                      <div
                        key={idx}
                        style={{
                          padding: "0.5rem",
                          background: "#f5f5f5",
                          marginBottom: "0.5rem",
                          borderRadius: "4px",
                          display: "flex",
                          justifyContent: "space-between",
                          alignItems: "center",
                        }}
                      >
                        <span>
                          {rule.type} {rule.value ? `(${rule.value})` : ""} -{" "}
                          {rule.enabled ? "Enabled" : "Disabled"}
                        </span>
                        <button
                          onClick={() => {
                            const updatedRules = actionModal.data.rules.filter(
                              (_, i) => i !== idx
                            );
                            setActionModal((prev) => ({
                              ...prev,
                              data: { ...prev.data, rules: updatedRules },
                            }));
                          }}
                          style={{
                            background: "#ff4444",
                            color: "white",
                            border: "none",
                            borderRadius: "4px",
                            padding: "2px 8px",
                            cursor: "pointer",
                          }}
                        >
                          Delete
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Concatenate Columns */}
              {actionModal.type === "concatenate" && (
                <div>
                  <p>Concatenate Columns</p>
                  <div style={{ marginBottom: "1rem" }}>
                    <label>Source Columns:</label>
                    <select
                      multiple
                      value={actionModal.data.sourceColumns}
                      onChange={(e) => {
                        const selected = Array.from(
                          e.target.selectedOptions,
                          (option) => option.value
                        );
                        setActionModal((prev) => ({
                          ...prev,
                          data: { ...prev.data, sourceColumns: selected },
                        }));
                      }}
                      style={{
                        width: "100%",
                        padding: "8px",
                        border: "1px solid #ddd",
                        borderRadius: "4px",
                        marginBottom: "0.5rem",
                      }}
                    >
                      {currentAttributes.map((attr) => (
                        <option key={attr} value={attr}>
                          {attr}
                        </option>
                      ))}
                    </select>
                    <small>Hold Ctrl/Cmd to select multiple columns</small>
                  </div>
                  <div style={{ marginBottom: "1rem" }}>
                    <label>Target Column Name:</label>
                    <input
                      type="text"
                      placeholder="e.g., full_name"
                      value={actionModal.data.targetColumn}
                      onChange={(e) =>
                        setActionModal((prev) => ({
                          ...prev,
                          data: {
                            ...prev.data,
                            targetColumn: e.target.value,
                          },
                        }))
                      }
                      style={{
                        width: "100%",
                        padding: "8px",
                        border: "1px solid #ddd",
                        borderRadius: "4px",
                      }}
                    />
                  </div>
                  <div style={{ marginBottom: "1rem" }}>
                    <label>Separator:</label>
                    <input
                      type="text"
                      placeholder="e.g., space, comma, dash"
                      value={actionModal.data.separator}
                      onChange={(e) =>
                        setActionModal((prev) => ({
                          ...prev,
                          data: { ...prev.data, separator: e.target.value },
                        }))
                      }
                      style={{
                        width: "100%",
                        padding: "8px",
                        border: "1px solid #ddd",
                        borderRadius: "4px",
                      }}
                    />
                  </div>
                  <div style={{ marginBottom: "1rem" }}>
                    <h4>Existing Concatenation Rules:</h4>
                    {concatenationRules.map((rule) => (
                      <div
                        key={rule.id}
                        style={{
                          padding: "0.5rem",
                          background: "#f5f5f5",
                          marginBottom: "0.5rem",
                          borderRadius: "4px",
                          display: "flex",
                          justifyContent: "space-between",
                          alignItems: "center",
                        }}
                      >
                        <span>
                          {rule.sourceColumns.join(" + ")} → {rule.targetColumn}
                        </span>
                        <button
                          onClick={() => handleDeleteConcatenationRule(rule.id)}
                          style={{
                            background: "#ff4444",
                            color: "white",
                            border: "none",
                            borderRadius: "4px",
                            padding: "2px 8px",
                            cursor: "pointer",
                          }}
                        >
                          Delete
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </Modal.Body>
            <Modal.Footer>
              <Button
                variant="outline-secondary"
                onClick={() => setShowRenameModal(false)}
              >
                Cancel
              </Button>
              <Button onClick={handleSaveAction} variant="primary">
                Save
              </Button>
            </Modal.Footer>
          </Modal>
        )}

        {/* PySpark Code Modal */}
        {pysparkModal.open && (
          <Modal
            show={showPySparkModal}
            onHide={() => setShowPySparkModal(false)}
            centered
            backdrop="static"
          >
            <Modal.Header closeButton>
              <Modal.Title>Generated PySpark Code</Modal.Title>
            </Modal.Header>
            <div className="mx-4 px-3 py-2 bg-light rounded border small fw-medium font-secondary text-center">
              PySpark code generated based on all your rules and
              transformations:
            </div>

            <Modal.Body>
              <pre>{pysparkModal.code}</pre>
            </Modal.Body>
            <Modal.Footer>
              <Button
                variant="outline-secondary btn-icon"
                title="Copy Code"
                size="sm"
                onClick={() => {
                  navigator.clipboard.writeText(pysparkModal.code);
                  alert("Code copied to clipboard!");
                }}
              >
                <BiCopyAlt />
              </Button>
            </Modal.Footer>
          </Modal>
        )}

        {/* SQL Code Modal */}
        {sqlModal.open && (
          <Modal
            show={showSqlModal}
            onHide={() => setShowSqlModal(false)}
            centered
            scrollable
            size="lg"
            backdrop="static"
          >
            <Modal.Header closeButton>
              <Modal.Title>Generated SQL Code</Modal.Title>
            </Modal.Header>

            <div className="mx-4 px-3 py-2 bg-light rounded border small fw-medium font-secondary text-center">
              SQL code generated based on all your rules and transformations:
            </div>

            <Modal.Body>
              <pre>{sqlModal.code}</pre>
            </Modal.Body>
            <Modal.Footer>
              <Button
                variant="outline-secondary btn-icon"
                title="Copy Code"
                size="sm"
                onClick={() => {
                  navigator.clipboard.writeText(sqlModal.code);
                  alert("SQL code copied to clipboard!");
                }}
              >
                <BiCopyAlt />
              </Button>
            </Modal.Footer>
          </Modal>
        )}

        {/* Entity NLP Modal */}
        {entityNLPModal.open && (
          <Modal
            show={showNlpModal}
            onHide={() => setShowNlpModal(false)}
            centered
            scrollable
            backdrop="static"
          >
            <Modal.Header closeButton>
              <Modal.Title>Entity-Level NLP Processing</Modal.Title>
            </Modal.Header>
            <Modal.Body>
              <p>
                Describe the NLP processing you want to apply to this entity.
                For example: "Convert all text columns to lowercase, remove
                special characters from email addresses, and extract sentiment
                from customer reviews."
              </p>
              <Form.Group className="mb-4">
                <Form.Control
                  as="textarea"
                  value={entityNLPModal.text}
                  onChange={(e) =>
                    setEntityNLPModal({
                      ...entityNLPModal,
                      text: e.target.value,
                    })
                  }
                  placeholder="Enter your NLP processing requirements..."
                  style={{ minHeight: "200px" }}
                />
              </Form.Group>

              <h4 className="text-large fw-semi-bold">
                Current Entity NLP Rules:
              </h4>
              {entityNLPRules.length === 0 ? (
                <Alert variant="info">
                  No entity-level NLP rules defined yet.
                </Alert>
              ) : (
                entityNLPRules.map((rule) => (
                  <div
                    key={rule.id}
                    className="bg-light border rounded p-3 d-flex mb-2 gap-3"
                  >
                    <div style={{ flex: 1 }}>
                      <div>
                        {rule.enabled ? (
                          <div className="d-inline-flex gap-2 align-items-center">
                            <BiSolidCheckCircle color="green" size={24} />
                            Enabled
                          </div>
                        ) : (
                          <div className="d-inline-flex gap-2 align-items-center">
                            <BiSolidXCircle color="red" size={24} />
                            Disabled
                          </div>
                        )}
                      </div>
                      <div className="font-secondary mt-3">{rule.text}</div>
                      <p className="text-muted small mt-1 mb-0">
                        Created: {new Date(rule.createdAt).toLocaleString()}
                      </p>
                    </div>
                    <Button
                      variant="outline-secondary btn-icon"
                      size="sm"
                      onClick={() => deleteEntityNLPRule(rule.id)}
                    >
                      <BiTrash />
                    </Button>
                  </div>
                ))
              )}
            </Modal.Body>

            <Modal.Footer>
              <Button
                variant="outline-secondary"
                onClick={() => setShowNlpModal(false)}
              >
                Cancel
              </Button>
              <Button onClick={saveEntityNLP} variant="primary">
                Save NLP Rule
              </Button>
            </Modal.Footer>
          </Modal>
        )}

        {/* Description Modal */}
        {descriptionModal.open && (
          <Offcanvas
            backdrop="static"
            show={showDescModal}
            onHide={() => setShowDescModal(false)}
            placement="end"
          >
            <Offcanvas.Header closeButton>
              <Offcanvas.Title>Column Description</Offcanvas.Title>
              <div className="d-flex align-items-center gap-2">
                <Image src={curatedFile} alt="" />
                <span>{entityName}</span>
                <Image src={curatedAi} alt="" />
                <Image src={curatedFile} alt="" />
                <span>{entityName}</span>
              </div>
            </Offcanvas.Header>

            <Offcanvas.Body>
              <Form.Group className="mb-3">
                <Form.Label>Column:</Form.Label>
                <Form.Select
                  value={descriptionModal.column}
                  onChange={(e) => {
                    const selectedColumn = e.target.value;
                    let description = "";

                    if (selectedColumn) {
                      // Get description from user-saved descriptions first, then fall back to auto-generated
                      const userDescription =
                        columnDescriptions[selectedColumn];
                      const autoGeneratedDescription =
                        schemaDescriptions[selectedColumn];
                      description =
                        userDescription || autoGeneratedDescription || "";
                    }

                    setDescriptionModal((prev) => ({
                      ...prev,
                      column: selectedColumn,
                      description: description,
                    }));
                  }}
                >
                  <option value="">Select a column to edit description</option>
                  {currentAttributes.map((attr) => (
                    <option key={attr} value={attr}>
                      {attr}{" "}
                      {columnDescriptions[attr]
                        ? "(user-saved)"
                        : schemaDescriptions[attr]
                        ? "(auto-generated)"
                        : ""}
                    </option>
                  ))}
                </Form.Select>
              </Form.Group>

              <Form.Group className="mb-3">
                <Form.Label className="d-inline-flex gap-2 align-items-center">
                  Description:
                  {!columnDescriptions[descriptionModal.column] &&
                    schemaDescriptions[descriptionModal.column] && (
                      <Badge bg="success">Auto-generated</Badge>
                    )}
                </Form.Label>

                <div className="gradient-textarea">
                  <Form.Control
                    as="textarea"
                    className="gradient-border"
                    value={descriptionModal.description}
                    onChange={(e) =>
                      setDescriptionModal((prev) => ({
                        ...prev,
                        description: e.target.value,
                      }))
                    }
                    placeholder="Enter column description..."
                  />
                  <div className="ai-icon">
                    <Image src={aiIcon} alt="" width={30} />
                  </div>
                </div>
              </Form.Group>

              <div className="text-end">
                <Button variant="primary" onClick={saveColumnDescription}>
                  Save & Submit
                </Button>
              </div>

              {/* <h5 className="fw-semi-bold">Existing Descriptions:</h5>
              {Object.keys(columnDescriptions).length === 0 ? (
                <Alert variant="info mt-3">
                  <div className="alert-icon">
                    <BiInfoCircle size={24} />
                  </div>
                  <div className="alert-text">
                    No column descriptions defined yet.
                  </div>
                </Alert>
              ) : (
                <div style={{ maxHeight: "200px", overflow: "auto" }}>
                  {Object.entries(columnDescriptions).map(
                    ([column, description]) => (
                      <div
                        key={column}
                        className="bg-light p-3 rounded border mb-2"
                      >
                        <p className="mb-1 fw-medium">{column}</p>
                        <p>{description}</p>
                        <div className="d-flex gap-2 justify-content-end align-items-center">
                          <Button
                            variant="light btn-icon"
                            size="sm"
                            title="Edit"
                            onClick={() => {
                              setDescriptionModal({
                                open: true,
                                column: column,
                                description: description,
                              });
                            }}
                          >
                            <BiPencil />
                          </Button>
                          <Button
                            variant="light btn-icon text-danger"
                            size="sm"
                            title="Delete"
                            onClick={() => deleteColumnDescription(column)}
                          >
                            <BiTrash />
                          </Button>
                        </div>
                      </div>
                    )
                  )}
                </div>
              )} */}
            </Offcanvas.Body>
          </Offcanvas>
        )}

        {/* Consumption Files Modal */}
        {consumptionFilesModal.open && (
          <Modal
            show={showConsumptionModal}
            onHide={() => setShowConsumptionModal(false)}
            centered
            size="xl"
            backdrop="static"
          >
            <Modal.Header closeButton>
              <Modal.Title>Consumption Files</Modal.Title>
            </Modal.Header>

            <Modal.Body>
              <p>
                Generated consumption files from gold data with applied
                transformations:
              </p>

              {consumptionFilesModal.files.length === 0 ? (
                <div className="text-muted">
                  <p>No consumption files found.</p>
                  <p>Generate a consumption file first to see it here.</p>
                </div>
              ) : (
                <div className="table-view">
                  <Table responsive>
                    <thead>
                      <tr>
                        <th>File Name</th>
                        <th>Entity Name</th>
                        <th>Size</th>
                        <th>Last Modified</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {consumptionFilesModal.files.map((file, index) => (
                        <tr key={index}>
                          <td>
                            <strong>{file.fileName}</strong>
                          </td>
                          <td>{file.entityName}</td>
                          <td className="text-nowrap">
                            {file.size
                              ? `${(file.size / 1024).toFixed(2)} KB`
                              : "N/A"}
                          </td>
                          <td className="text-nowrap">
                            {file.lastModified
                              ? new Date(file.lastModified).toLocaleString()
                              : "N/A"}
                          </td>
                          <td>
                            <div className="d-flex gap-2">
                              <Button
                                variant="outline-secondary btn-icon"
                                size="sm"
                                title="Download"
                                onClick={() => window.open(file.url, "_blank")}
                              >
                                <BiDownload />
                              </Button>
                              <Button
                                variant="outline-secondary btn-icon"
                                size="sm"
                                title="Copy URL"
                                onClick={() => {
                                  navigator.clipboard.writeText(file.url);
                                  alert("File URL copied to clipboard!");
                                }}
                              >
                                <BiCopyAlt />
                              </Button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </Table>
                </div>
              )}
            </Modal.Body>
          </Modal>
        )}
      </div>
    </>
  );
}

export default EditConsumptionEntityMappingsPage;
