import { FlowConfig } from '../../components/modals/CreateFlowModal';
import {
  ICodeGenerator,
  CodeGenerationOptions,
  CodeGenerationResult,
  GeneratedArtifact,
} from '../../types/codeGeneration';

export class DatabricksGenerator implements ICodeGenerator {
  validate(flow: FlowConfig): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!flow.source.schema || !flow.source.table) {
      errors.push('Source table information is incomplete');
    }

    if (!flow.target.schema || !flow.target.table) {
      errors.push('Target table information is incomplete');
    }

    if (!flow.columnMappings || flow.columnMappings.length === 0) {
      errors.push('No column mappings defined');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  async generate(
    flow: FlowConfig,
    options: CodeGenerationOptions
  ): Promise<CodeGenerationResult> {
    const artifacts: GeneratedArtifact[] = [];
    const warnings: string[] = [];

    // Validate flow before generation
    const validation = this.validate(flow);
    if (!validation.valid) {
      throw new Error(`Flow validation failed: ${validation.errors.join(', ')}`);
    }

    // Generate Delta Live Tables pipeline
    const dltPython = this.generateDLTPipeline(flow, options);
    artifacts.push({
      type: 'python',
      filename: `${flow.target.table}_dlt.py`,
      content: dltPython,
      language: 'python',
    });

    // Generate Spark SQL alternative
    const sparkSQL = this.generateSparkSQL(flow, options);
    artifacts.push({
      type: 'sql',
      filename: `${flow.target.table}_spark.sql`,
      content: sparkSQL,
      language: 'sql',
    });

    // Generate notebook if requested
    if (options.includeDocs) {
      const notebook = this.generateNotebook(flow);
      artifacts.push({
        type: 'config',
        filename: `${flow.target.table}_notebook.json`,
        content: notebook,
        language: 'json',
      });
    }

    return {
      artifacts,
      warnings,
      metadata: {
        generatedAt: new Date().toISOString(),
        flowId: flow.id,
        platform: 'databricks',
      },
    };
  }

  private generateDLTPipeline(flow: FlowConfig, options: CodeGenerationOptions): string {
    const { source, target, columnMappings = [], description } = flow;
    const materializationType = options.materializationType || 'table';

    // Build column selections
    const columnSelections = columnMappings
      .map((mapping) => {
        const expr = mapping.transformationExpression || mapping.sourceColumn;
        // Convert SQL syntax to PySpark syntax
        const pysparkExpr = this.convertToPySpark(expr, mapping.sourceColumn);
        return `        ${pysparkExpr}.alias("${mapping.targetColumn}")`;
      })
      .join(',\n');

    // Build expectations (data quality checks)
    const expectations = this.generateExpectations(columnMappings);

    const decorator =
      materializationType === 'view'
        ? '@dlt.view'
        : materializationType === 'incremental'
        ? `@dlt.table(
    name="${target.table}",
    comment="${description}",
    table_properties={
        "quality": "gold",
        "pipelines.autoOptimize.managed": "true"
    }
)`
        : `@dlt.table(
    name="${target.table}",
    comment="${description}"
)`;

    return `# Databricks Delta Live Tables Pipeline
# Generated by Dataflow UI
# Source: ${source.fullPath}
# Target: ${target.fullPath}

import dlt
from pyspark.sql import functions as F

${decorator}${expectations}
def ${target.table}():
    """
    ${description}
    """
    return (
        dlt.read("${source.schema}_${source.table}")
        .select(
${columnSelections}
        )
    )

# Source table definition
@dlt.table(
    name="${source.schema}_${source.table}",
    comment="Source table for ${flow.name}"
)
def source_${source.table}():
    return spark.table("${source.schema}.${source.table}")
`;
  }

  private convertToPySpark(sqlExpr: string, sourceColumn: string): string {
    // Convert common SQL functions to PySpark
    let pysparkExpr = sqlExpr;

    // CAST conversions
    pysparkExpr = pysparkExpr.replace(/CAST\((\w+) AS (\w+)\)/gi, 'F.col("$1").cast("$2")');

    // String functions
    pysparkExpr = pysparkExpr.replace(/TRIM\((\w+)\)/gi, 'F.trim(F.col("$1"))');
    pysparkExpr = pysparkExpr.replace(/UPPER\((\w+)\)/gi, 'F.upper(F.col("$1"))');
    pysparkExpr = pysparkExpr.replace(/LOWER\((\w+)\)/gi, 'F.lower(F.col("$1"))');

    // Hash functions
    pysparkExpr = pysparkExpr.replace(/SHA2\((\w+), (\d+)\)/gi, 'F.sha2(F.col("$1"), $2)');

    // Date functions
    pysparkExpr = pysparkExpr.replace(/TO_DATE\((\w+), '([^']+)'\)/gi, 'F.to_date(F.col("$1"), "$2")');

    // Coalesce
    pysparkExpr = pysparkExpr.replace(/COALESCE\((\w+), '([^']+)'\)/gi, 'F.coalesce(F.col("$1"), F.lit("$2"))');

    // If no transformation, just reference the column
    if (pysparkExpr === sourceColumn) {
      pysparkExpr = `F.col("${sourceColumn}")`;
    }

    return pysparkExpr;
  }

  private generateExpectations(columnMappings: any[]): string {
    const idColumn = columnMappings.find((m) => m.targetColumn.toLowerCase().includes('id'));

    if (!idColumn) return '';

    return `
@dlt.expect_or_fail("valid_${idColumn.targetColumn}", "${idColumn.targetColumn} IS NOT NULL")
@dlt.expect("valid_row_count", "COUNT(*) > 0")`;
  }

  private generateSparkSQL(flow: FlowConfig, _options: CodeGenerationOptions): string {
    const { source, target, columnMappings = [] } = flow;

    const columnSelections = columnMappings
      .map((mapping) => {
        const expr = mapping.transformationExpression || mapping.sourceColumn;
        return `    ${expr} AS ${mapping.targetColumn}`;
      })
      .join(',\n');

    return `-- Databricks Spark SQL
-- Generated by Dataflow UI
-- ${flow.description}

CREATE OR REPLACE TABLE ${target.schema}.${target.table}
USING DELTA
COMMENT '${flow.description}'
AS
SELECT
${columnSelections}
FROM ${source.schema}.${source.table};

-- Optimize table
OPTIMIZE ${target.schema}.${target.table};

-- Add Z-Order if there's an ID column
-- OPTIMIZE ${target.schema}.${target.table} ZORDER BY (id);
`;
  }

  private generateNotebook(flow: FlowConfig): string {
    const notebook = {
      cells: [
        {
          cell_type: 'markdown',
          source: [
            `# ${flow.name}\n`,
            `\n`,
            `${flow.description}\n`,
            `\n`,
            `**Source:** \`${flow.source.fullPath}\`\n`,
            `**Target:** \`${flow.target.fullPath}\`\n`,
            `**Generated:** ${new Date().toISOString()}\n`,
          ],
        },
        {
          cell_type: 'code',
          source: [
            `# Import libraries\n`,
            `from pyspark.sql import functions as F\n`,
            `import dlt\n`,
          ],
        },
        {
          cell_type: 'code',
          source: [`# Run the DLT pipeline\n`, `# See ${flow.target.table}_dlt.py for full code\n`],
        },
      ],
      metadata: {
        language_info: {
          name: 'python',
        },
      },
      nbformat: 4,
      nbformat_minor: 2,
    };

    return JSON.stringify(notebook, null, 2);
  }
}
