import { FlowConfig } from '../../components/modals/CreateFlowModal';
import {
  ICodeGenerator,
  CodeGenerationOptions,
  CodeGenerationResult,
  GeneratedArtifact,
} from '../../types/codeGeneration';

export class DbtGenerator implements ICodeGenerator {
  validate(flow: FlowConfig): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!flow.source.schema || !flow.source.table) {
      errors.push('Source table information is incomplete');
    }

    if (!flow.target.schema || !flow.target.table) {
      errors.push('Target table information is incomplete');
    }

    if (!flow.columnMappings || flow.columnMappings.length === 0) {
      errors.push('No column mappings defined');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  async generate(
    flow: FlowConfig,
    options: CodeGenerationOptions
  ): Promise<CodeGenerationResult> {
    const artifacts: GeneratedArtifact[] = [];
    const warnings: string[] = [];

    // Validate flow before generation
    const validation = this.validate(flow);
    if (!validation.valid) {
      throw new Error(`Flow validation failed: ${validation.errors.join(', ')}`);
    }

    // Generate dbt model SQL
    const modelSQL = this.generateModelSQL(flow, options);
    artifacts.push({
      type: 'sql',
      filename: `${flow.target.table}.sql`,
      content: modelSQL,
      language: 'sql',
    });

    // Generate dbt schema YAML
    const schemaYAML = this.generateSchemaYAML(flow);
    artifacts.push({
      type: 'yaml',
      filename: `schema.yml`,
      content: schemaYAML,
      language: 'yaml',
    });

    // Generate tests if requested
    if (options.includeTests) {
      const testsYAML = this.generateTestsYAML(flow);
      artifacts.push({
        type: 'yaml',
        filename: `${flow.target.table}_tests.yml`,
        content: testsYAML,
        language: 'yaml',
      });
    }

    // Generate sources YAML
    const sourcesYAML = this.generateSourcesYAML(flow);
    artifacts.push({
      type: 'yaml',
      filename: 'sources.yml',
      content: sourcesYAML,
      language: 'yaml',
    });

    return {
      artifacts,
      warnings,
      metadata: {
        generatedAt: new Date().toISOString(),
        flowId: flow.id,
        platform: 'dbt',
      },
    };
  }

  private generateModelSQL(flow: FlowConfig, options: CodeGenerationOptions): string {
    const { source, columnMappings = [] } = flow;
    const materializationType = options.materializationType || 'table';

    // Build column selections with transformations
    const columnSelections = columnMappings
      .map((mapping) => {
        const expr = mapping.transformationExpression || mapping.sourceColumn;
        return `    ${expr} AS ${mapping.targetColumn}`;
      })
      .join(',\n');

    // Build config
    const config = `{{
  config(
    materialized='${materializationType}',
    schema='${flow.target.schema}'${
      options.useIncrementalLoads && materializationType === 'incremental'
        ? `,
    unique_key='id'`
        : ''
    }
  )
}}`;

    // Build incremental logic
    let incrementalLogic = '';
    if (options.useIncrementalLoads && materializationType === 'incremental') {
      incrementalLogic = `
{% if is_incremental() %}
WHERE updated_at > (SELECT MAX(updated_at) FROM {{ this }})
{% endif %}`;
    }

    return `${config}

-- ${flow.description}
-- Generated by Dataflow UI
-- Source: ${source.fullPath}

WITH source_data AS (
    SELECT *
    FROM {{ source('${source.schema}', '${source.table}') }}${incrementalLogic}
)

SELECT
${columnSelections}
FROM source_data
`;
  }

  private generateSchemaYAML(flow: FlowConfig): string {
    const { target, columnMappings = [], description } = flow;

    const columns = columnMappings
      .map((mapping) => {
        return `      - name: ${mapping.targetColumn}
        description: "Transformed from source.${mapping.sourceColumn} using ${mapping.transformationType}"`;
      })
      .join('\n');

    return `version: 2

models:
  - name: ${target.table}
    description: "${description}"
    columns:
${columns}
`;
  }

  private generateTestsYAML(flow: FlowConfig): string {
    const { target, columnMappings = [] } = flow;

    // Find ID column for unique tests
    const idColumn = columnMappings.find((m) => m.targetColumn.toLowerCase().includes('id'));

    let tests = `version: 2

models:
  - name: ${target.table}
    tests:
      - dbt_utils.recency:
          datepart: day
          field: created_at
          interval: 1
`;

    if (idColumn) {
      tests += `
    columns:
      - name: ${idColumn.targetColumn}
        tests:
          - unique
          - not_null
`;
    }

    // Add not_null tests for key columns
    const requiredColumns = columnMappings.filter(
      (m) =>
        !m.targetColumn.toLowerCase().includes('optional') &&
        m.targetColumn !== idColumn?.targetColumn
    );

    if (requiredColumns.length > 0) {
      requiredColumns.forEach((col) => {
        tests += `      - name: ${col.targetColumn}
        tests:
          - not_null
`;
      });
    }

    return tests;
  }

  private generateSourcesYAML(flow: FlowConfig): string {
    const { source } = flow;

    return `version: 2

sources:
  - name: ${source.schema}
    description: "Source schema for ${source.schema}"
    database: {{ target.database }}
    schema: ${source.schema}
    tables:
      - name: ${source.table}
        description: "Raw source table for ${flow.name}"
        columns:
          - name: id
            description: "Primary key"
            tests:
              - unique
              - not_null
`;
  }
}
