import { FlowConfig } from '../../components/modals/CreateFlowModal';
import {
  ICodeGenerator,
  CodeGenerationOptions,
  CodeGenerationResult,
  GeneratedArtifact,
} from '../../types/codeGeneration';

export class SnowflakeGenerator implements ICodeGenerator {
  validate(flow: FlowConfig): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!flow.source.schema || !flow.source.table) {
      errors.push('Source table information is incomplete');
    }

    if (!flow.target.schema || !flow.target.table) {
      errors.push('Target table information is incomplete');
    }

    if (!flow.columnMappings || flow.columnMappings.length === 0) {
      errors.push('No column mappings defined');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  async generate(
    flow: FlowConfig,
    options: CodeGenerationOptions
  ): Promise<CodeGenerationResult> {
    const artifacts: GeneratedArtifact[] = [];
    const warnings: string[] = [];

    // Validate flow before generation
    const validation = this.validate(flow);
    if (!validation.valid) {
      throw new Error(`Flow validation failed: ${validation.errors.join(', ')}`);
    }

    // Generate main transformation SQL
    const transformSQL = this.generateTransformationSQL(flow, options);
    artifacts.push({
      type: 'sql',
      filename: `${flow.target.table}_transform.sql`,
      content: transformSQL,
      language: 'sql',
    });

    // Generate DDL for target table
    const ddlSQL = this.generateDDL(flow);
    artifacts.push({
      type: 'sql',
      filename: `${flow.target.table}_ddl.sql`,
      content: ddlSQL,
      language: 'sql',
    });

    // Generate tests if requested
    if (options.includeTests) {
      const testSQL = this.generateTests(flow);
      artifacts.push({
        type: 'sql',
        filename: `${flow.target.table}_tests.sql`,
        content: testSQL,
        language: 'sql',
      });
    }

    // Add warnings for unapproved mappings
    const unapprovedMappings = flow.columnMappings?.filter((m) => !m.isApproved) || [];
    if (unapprovedMappings.length > 0) {
      warnings.push(
        `${unapprovedMappings.length} column mapping(s) are not approved. Review before deploying.`
      );
    }

    return {
      artifacts,
      warnings,
      metadata: {
        generatedAt: new Date().toISOString(),
        flowId: flow.id,
        platform: 'snowflake',
      },
    };
  }

  private generateTransformationSQL(flow: FlowConfig, options: CodeGenerationOptions): string {
    const { source, target, columnMappings = [] } = flow;

    // Build column selection with transformations
    const columnSelections = columnMappings
      .map((mapping) => {
        const expr = mapping.transformationExpression || mapping.sourceColumn;
        return `    ${expr} AS ${mapping.targetColumn}`;
      })
      .join(',\n');

    // Determine materialization
    const materializationType = options.materializationType || 'table';
    const createStatement =
      materializationType === 'view'
        ? `CREATE OR REPLACE VIEW ${target.schema}.${target.table} AS`
        : materializationType === 'incremental'
        ? `CREATE OR REPLACE TABLE ${target.schema}.${target.table} AS`
        : `CREATE OR REPLACE TABLE ${target.schema}.${target.table} AS`;

    // Build the SQL
    let sql = `-- ${flow.name}
-- Generated by Dataflow UI
-- Platform: Snowflake
-- Source: ${source.fullPath}
-- Target: ${target.fullPath}
-- Description: ${flow.description}
-- Generated: ${new Date().toISOString()}

${createStatement}
SELECT
${columnSelections}
FROM ${source.schema}.${source.table}`;

    // Add incremental logic if needed
    if (options.useIncrementalLoads && materializationType === 'incremental') {
      sql += `\nWHERE updated_at > (
    SELECT COALESCE(MAX(updated_at), '1970-01-01'::TIMESTAMP)
    FROM ${target.schema}.${target.table}
)`;
    }

    sql += ';\n';

    return sql;
  }

  private generateDDL(flow: FlowConfig): string {
    const { target, columnMappings = [] } = flow;

    // Infer column definitions from mappings
    const columnDefs = columnMappings
      .map((mapping) => {
        // Simple type inference (in production, would use actual column metadata)
        let snowflakeType = 'VARCHAR';
        const expr = mapping.transformationExpression || '';

        if (expr.includes('CAST') && expr.includes('NUMBER')) {
          snowflakeType = 'NUMBER';
        } else if (expr.includes('CAST') && expr.includes('INT')) {
          snowflakeType = 'INTEGER';
        } else if (expr.includes('TO_DATE') || expr.includes('DATE')) {
          snowflakeType = 'DATE';
        } else if (expr.includes('TIMESTAMP')) {
          snowflakeType = 'TIMESTAMP';
        } else if (expr.includes('SHA2')) {
          snowflakeType = 'VARCHAR(64)';
        }

        return `    ${mapping.targetColumn} ${snowflakeType}`;
      })
      .join(',\n');

    return `-- DDL for ${target.fullPath}
-- Generated by Dataflow UI

CREATE TABLE IF NOT EXISTS ${target.schema}.${target.table} (
${columnDefs}
);

-- Add comments
COMMENT ON TABLE ${target.schema}.${target.table} IS '${flow.description}';
`;
  }

  private generateTests(flow: FlowConfig): string {
    const { target, columnMappings = [] } = flow;

    let tests = `-- Data Quality Tests for ${target.fullPath}
-- Generated by Dataflow UI

-- Test 1: Row count check
SELECT
    '${target.table}: Row Count' AS test_name,
    COUNT(*) AS row_count,
    CASE
        WHEN COUNT(*) > 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS status
FROM ${target.schema}.${target.table};

`;

    // Generate null checks for non-nullable columns
    const requiredColumns = columnMappings.filter((m) => !m.targetColumn.toLowerCase().includes('optional'));

    if (requiredColumns.length > 0) {
      tests += `-- Test 2: NULL value checks
SELECT
    '${target.table}: NULL Check' AS test_name,
`;

      tests += requiredColumns
        .map(
          (m) => `    SUM(CASE WHEN ${m.targetColumn} IS NULL THEN 1 ELSE 0 END) AS ${m.targetColumn}_nulls`
        )
        .join(',\n');

      tests += `
FROM ${target.schema}.${target.table};

`;
    }

    // Test for duplicate keys (if id column exists)
    const idColumn = columnMappings.find((m) => m.targetColumn.toLowerCase().includes('id'));
    if (idColumn) {
      tests += `-- Test 3: Duplicate key check
SELECT
    '${target.table}: Duplicate Keys' AS test_name,
    COUNT(*) - COUNT(DISTINCT ${idColumn.targetColumn}) AS duplicate_count,
    CASE
        WHEN COUNT(*) = COUNT(DISTINCT ${idColumn.targetColumn}) THEN 'PASS'
        ELSE 'FAIL'
    END AS status
FROM ${target.schema}.${target.table};
`;
    }

    return tests;
  }
}
